import LocalizedStrings from 'react-localization';

const yearNow = new Date().getFullYear();

const localizedStrings = new LocalizedStrings({
  pt: {
  	noOccurrences: "Sem ocorrências",
	occurrences: "ocorrências",
    addANewStopPlace: "Adicionar Ponto de Parada",
    selectANewStopPlace: "Selecione abaixo o novo ponto de parada:",
    addNewStopPlace: "Adicione um novo Ponto de Parada",
    searchByIdentification: "Buscar pela identificação",
    ocrmRoute: "Possível Rota",
    reportKm: "Relatório de KM",
    numberAddress: "Nº",
    times: "Vezes",
    oneTime: "Vez",
    Sunday: "Domingo",
    Monday: "Segunda-Feira",
    Tuesday: "Terça-Feira",
    Wednesday: "Quarta-Feira",
    Thursday: "Quinta-Feira",
    Friday: "Sexta-Feira",
    Saturday: "Sábado",
    routeOnGoing: "Rota em Andamento",
		thisRouteIsOnGoing: "Essa rota está em andamento",
		mayContainRetainedPoints: "podem conter pontos retidos, ou eventos, ainda não transmitidos.",
    vehicleIsOnRoute: "Veículo em rota. A data e hora aparecerão aqui assim que veículo for desligado.",
    failTo: "Falha ao ",
    failToUpdateOdometer: "atualizar o odometro",
    sendSuccess: "Relatório enviado para os e-mails com sucesso.",
    addEmail: "Adicione um email",
    sendReport: "Enviar Relatório",
    typeEmailsBellow: "Digite os e-mails para o envio do relatório abaixo:",
    errorOnSendEmail: "Erro ao enviar o relatório , tente novamente.",
    sendReportbyEmail: "Enviar relatório por e-mail",
    clickHereToSenByEmail: "para enviar o relatório por e-mail.",
    notFoundAuditReport: "Não foi encontrado nenhum ponto desse veículo no período selecionado.",
    sended: "Enviado",
    startNightTime: "Hora noturna inicial: ",
    endNightTime: "Hora final do dia seguinte: ",
    action: "Ação",
    viewAddress: 'Ver endereço',
    typeStatusOfMarker: {
      on:'ligado',
      off:'desligado',
      noSignal:'sem-sinal',
      noSignalPermanent: 'sem-sinal-permanente'
    },
    notIdentified: 'Não identificado',
    specialPlace: "Local Especial",
    noRegistered: 'Nenhum cadastrado',
    soon: "Em breve",
    footerMessage:'Contele Rastreador é a solução inteligente para o aumento de produtividade e redução de custos da sua frota.',
    messagesFormPageLoading: [
      'Rotas inteligentes',
      'Relatórios precisos',
      'Redução de custos',
      'Aumento de produtividade',
      'Fim dos Abusos no Volante',
      'Gestão Inteligente da Frota',
      'Simplificando Dados da Frota',
      'Proteção Jurídica da Empresa',
      'Monitoramento em Tempo Real',
      'Notificações de Eventos',
      'Relatórios Vitalícios',
      'Vencimento das CNH’s',
      'Velocidade Máxima dos Veículos'],
    maxColumns: "Selecione no máximo 6 colunas",
    sms: "SMS",
    blocked: "Bloqueado",
    lockPending: "Bloqueio Pendente",
    unlockPending: "Desbloqueio Pendente",
    solicitationTitle: "Veja a listagem de Solicitações de Veículos, e aprove ou recuse as solicitações. Seu Cliente receberá uma notificação.",
    solicitationLink: "https://help.contelerastreador.com.br/pt-br/article/solicitacoes-de-veiculos-9zvhzj/",
    placeDescription: "Para criar um Serviço Logístico, é necessário que você cadastre Locais, Pessoas ou Objetos.",
    clientDescription: "Para criar um Serviço Logístico, é necessário que você cadastre os Clientes que receberão esses serviços.",
    minCpfCpjError: "Digite um cpf/cnpj válido.",
    minZipcode: "Digite um cpf válido.",
    accessNotAllowed: "Ops, você já nesta organização!",
    labelOfModalChangeOrganization: 'Para trocar de organização, pesquise pelo nome ou CNPJ e clique em "Acessar painel".',
    searchByNameOrCnpj: 'Pesquise pelo nome ou CNPJ',
    accessPanel: 'Acessar Painel',
    changeOrganization: "Trocar Empresa",
    currentOrg: "Org. atual",
    hours: 'horas',
    hoursAndMinutes: 'horas e 30 minutos',
    intervalSettingInMinutes: 'Intervalo Configurado: 30 minutos',
    intervalSetting: 'Intervalo Configurado:',
    vehicleStatusDesconected: "Desconectado da Alimentação Principal",
    bestRoute: "Melhor Rota",
    velocity: "Velocidade",
    view: "Mostrar",
    hide: "Ocultar",
    details: "Detalhes",
    driverDetails: "Detalhes do Motorista",
    vehicleDetails: "Detalhes do Veículo",
    messageCopy: "Item copiado com sucesso!",
    messageCopyError: "Erro ao copiar!",
    messageVehicleInactiveSevenDays: "Este veículo está sem comunicação há mais de 07 dias",
		noFilter: "Nenhum filtro",
    clickNext: "Clique no ícone ao lado para abrir Relatório de Rotas",
    helperIndicate: "Indique e Ganhe",
    helperHelp: "Central de Ajuda",
    helperCertifications: "Certificações",
    helperNew: "Novidades do Sistema",
    registerYourIdea: "Registre sua ideia",
    googlePlay: "Google Play",
    appStore: "App Store",
    appDriver: "App Driver",
    helpLink: {
      commandBlock:
        "https://help.contelerastreador.com.br/pt-br/category/bloqueio-do-veiculo-1izgos0/",
      reports: {
        km:
          "https://help.contelerastreador.com.br/pt-br/article/relatorio-de-km-1chiy4g/?1584047383313",
        allDrivers:
          "https://help.contelerastreador.com.br/pt-br/article/relatorio-consolidado-de-todos-os-motoristas-1t0zma8/?1584047506557",
        driverPerRoute:
          "https://help.contelerastreador.com.br/pt-br/article/relatorio-do-motorista-por-rota-1mzom8/?1584047593180",
        driverPerDay:
          "https://help.contelerastreador.com.br/pt-br/article/relatorio-do-motorista-por-dia-13qnkmq/?1584047730296",
        fuel:
          "https://help.contelerastreador.com.br/pt-br/article/checklist-1iwutx/?1584654017725",
        registers:
          "https://help.contelerastreador.com.br/pt-br/article/abastecimentos-fodz9j/",
        checklist:
          "https://help.contelerastreador.com.br/pt-br/article/checklist-do-veiculo-1iwutx/",
        audit:
          "https://help.contelerastreador.com.br/pt-br/article/relatorio-de-auditoria-14mhy16/?1591812139730",
        productivity:
          "https://help.contelerastreador.com.br/pt-br/article/relatorio-de-produtividade-gi7t9t/?1584047989315",
        vehicleStatus:
          "https://help.contelerastreador.com.br/pt-br/article/relatorio-de-status-dos-veiculos-1mknmv2/?1589988687167",
        vehicleEvents:
          "https://help.contelerastreador.com.br/pt-br/article/relatorio-de-eventos-1k6l506/",
        routes:
          "https://help.contelerastreador.com.br/pt-br/article/relatorio-de-rota-1ertg8x/?1591736172319",
        events:
          "https://help.contelerastreador.com.br/pt-br/article/relatorio-de-eventos-1k6l506/?1584048581804",
      },
      fence:
        "https://help.contelerastreador.com.br/pt-br/article/cerca-eletronica-xl6b26/",
      groups:
        "https://help.contelerastreador.com.br/pt-br/article/grupos-de-veiculos-u8o9yz/?1584050043040",
      vehicleHoursOfUse:
        "https://help.contelerastreador.com.br/pt-br/article/horario-de-utilizacao-do-veiculo-3gvvjb/",
      users:
        "https://help.contelerastreador.com.br/pt-br/article/hierarquias-de-acesso-ao-sistema-1a6j8my/",
      clients:
        "https://help.contelerastreador.com.br/pt-br/article/hierarquias-de-acesso-ao-sistema-1a6j8my/",
      drivers:
        "https://help.contelerastreador.com.br/pt-br/category/motoristas-10vytuq/",
      vehicles:
        "https://help.contelerastreador.com.br/pt-br/article/o-que-e-o-estado-ativado-e-desativado-do-veiculo-1d6utbc/",
      vehiclesEdit:
        "https://help.contelerastreador.com.br/pt-br/article/como-cadastrar-os-veiculos-pbu8g6/",
    },
    pending: {
      create: {
        fence: "Criando Cerca Eletrônica...",
        user: "Criando Usuário...",
        vehicle: "Criando Veículo...",
        driver: "Criando Motorista...",
        group: "Criando Grupo...",
        command: "Enviando Comando...",
        client: "Criando Cliente...",
        place: "Criando Local...",
        command: "Enviando Comando...",
      },
      update: {
        fence: "Atualizando Cerca Eletrônica...",
        user: "Atualizando Usuário...",
        vehicle: "Atualizando Veículo...",
        driver: "Atualizando Motorista...",
        group: "Atualizando Grupo...",
        client: "Atualizando Cliente...",
        place: "Atualizando Local...",
        solicitation: "Atualizando Solicitação...",
      },
      delete: {
        driver: "Deletando Motorista...",
      },
    },
    success: {
      create: {
        fence: "Cerca Eletrônica cadastrada com sucesso",
        user: "Usuário cadastrado com sucesso",
        vehicle: "Veículo cadastrado com sucesso",
        driver: "Motorista cadastrado com sucesso",
        group: "Grupo cadastrado com sucesso",
        command: "Comando enviado",
        client: "Cliente cadastrado com sucesso",
        place: "Local cadastrado com sucesso",
        solicitation: "Solicitação cadastrada com sucesso",
      },
      update: {
        fence: "Cerca Eletrônica atualizada com sucesso",
        user: "Usuário atualizado com sucesso",
        vehicle: "Veículo atualizado com sucesso",
        driver: "Motorista atualizado com sucesso",
        group: "Grupo atualizado com sucesso",
        client: "Cliente atualizado com sucesso",
        place: "Local atualizado com sucesso",
        solicitation: "Solicitação atualizada com sucesso",
      },
      delete: {
        driver: "Motorista deletado com sucesso",
        group: "Grupo deletado com sucesso",
      },
    },
    error: {
      user: {
        create: {
          409: "Já existe um Usuário cadastrado com esse e-mail. Por favor, tente novamente com um outro endereço.",
        }
      },
      create: {
        fence: "Problemas ao criar a Cerca Eletrônica",
        user: "Problemas ao criar o Usuário",
        vehicle: "Problemas ao criar o Veículo",
        driver: "Problemas ao criar o Motorista",
        group: "Problemas ao criar o Grupo",
        command: "Problemas ao enviar o Comando",
        fuel: "Problemas ao criar o Abastecimento",
        client: "Problemas ao criar o Cliente",
        place: "Problemas ao criar o Local",
      },
      update: {
        fence: "Problemas ao atualizar a Cerca Eletrônica",
        user: "Problemas ao atualizar o Usuário",
        vehicle: "Problemas ao atualizar o Veículo",
        driver: "Problemas ao atualizar o Motorista",
        group: "Problemas ao atualizar o Grupo",
        client: "Problemas ao atualizar o Cliente",
        place: "Problemas ao atualizar o Local",
        solicitation: "Problemas ao atualizar a Solicitação",
        plate_duplicated: "Placa do veiculo ja esta sendo utilizada.",
      },
      delete: {
        driver: "Problemas ao deletar o Motorista",
      },
      load: {
        route: "Tivemos problemas ao carregar a rota",
      },
      emailWrongFormat: "O email não está no formato correto",
      identificationDriverKeyAlreadyInUse:
        "Essa chave de identificação já está sendo utilizada em outro motorista",
      cnhAlreadyInUse: "Essa CNH já está sendo utilizada em outro motorista",
      codeHasToBeString: "A chave de acesso deve ser apenas texto",
      types: {
        shouldBeNumber: (val) => val + " deveria ser um número",
        haveRequiredProperty: (val) =>
          val + " é obrigatório",
        tagNameAlreadyExists: "O nome do grupo já existe",
        outOfPattern: "fora do padrão do sistema",
      },
    },
    volumetricUnitNames: {
      liter: "Litros",
      fluidounce: "Fluid Ounce",
      gill: "Gill",
      pint: "Pint",
      quart: "Quart",
      gallon: "Galões",
    },
    sendToDriverViaAppConfirmation: (driver) =>
      "Você está prestes a enviar a rota traçada para o aplicativo do " +
      driver +
      ". Deseja fazer o envio?",
    close: "Fechar",
    tag: "Etiqueta",
    noTagFound: "Nenhuma Etiqueta encontrada",
    selectATag: "Selecione uma etiqueta",
    recoveryPasswordSendToYourEmail:
      "O link para recuperar a senha foi enviado para seu email",
    disableVehicleAttentionTitle: "Atenção ! Você está prestes a desativar um veículo.",
    disableVehicleMessage: "Ao realizar essa ação, o veículo ficará oculto na listagem enquanto a opção 'Mostrar somente veículos ativos' estiver selecionada !",
    emailWrongOrDoestExists: "E-mail digitado errado ou não existe",
    clickOnMapToDrawFence: "Clique no mapa para desenhar sua cerca",
    migratingAModuleToAnotherVehicle: "A troca de Módulos exige cuidados:",
    migratingAModuleItemOne: "É aconselhada apenas para reparos ou em caso de mau funcionamento do módulo;",
    migratingAModuleItemTwo: "Após desvincular o módulo, não esquecer nenhum veículo sem um módulo atrelado;",
    migratingAModuleItemThree: "O veículo só pode ser vinculado a um módulo disponível (sendo vedado atribuir a um módulo já instalado em outro veículo);",
    migratingAModuleItemFour: "Um veículo não pode ser atribuído a mais de um Módulo.",
    migratingAVehicleToAnotherOrganization: "Migrar um veículo para outra Organização implica",
    migratingAVehicleItemOne: "O veículo não ficará mais disponível neste acesso e apenas os dados anteriores à alteração serão visíveis;",
    migratingAVehicleItemTwo: "O veículo passará para a Organização de Destino;",
    migratingAVehicleItemThree: "O veículo será atribuído como Novo na Organização de Destino e não possuirá ligações com o acesso anterior.",
    areYouSureUWantToContinue: "Você tem certeza que deseja continuar?",
    iAmAwareOfTheConsequencesOfThisAction: "Estou ciente das consequências desta ação.",
    downloadReady: "Fazer Download",
    modalMessageReady: "Seu link para download está pronto.",
    modalMessageNotFound: "Você não possui dados suficientes para realizar uma exportação ainda.",
    modalMessageProgress: "Ops, não é possível realizar essa importação! Você não possui dados suficientes para realizar uma exportação ainda.",
    messageModalPleaseWait: "Aguarde, seu relatório está sendo gerado..",
    loadingRoutes: "Carregando rotas...",
    loadingAddresses: "Carregando Endereços...",
    problemsWhenLoadingDate: "Ocorreram problemas ao carregar a data",
    problemsWhenLoadingData: "Ocorreram problemas ao carregar os dados",
    productNameContele: "Contele Rastreador",
    allVehicles: "Todos os Veículos",
    maintenancePlan: "Plano da Manutenção",
    maintenance: "Manutenção",
    supply: "Abastecimento",
    VehicleRequests: "Solicitações de Veículos",
    showDetails: "Mostrar Detalhado",
    seeReport: "Ver relatório",
    driversPerDay: "Motoristas por dia",
    vehiclesNoModule: "Não instalados",
    vehicleNoModule: "Não instalado",
    noCommunication: "Sem comunicação",
    vehicleNoUse: "Sem utilização",
    driversPerRoute: "Motoristas por rota",
    allDrivers: "Todos os motoristas",
		allGroups: "Todos os grupos",
    estimatedTime: "Tempo Estimado",
    admin: "Administrador",
    manager: "Gestor",
    viewer: "Visualizador",
    userWithPermissions: "Usuário com permissões",
    defaultUser: "Usuário",
    registers: "Registros",
    listVehices: "Lista de veículos",
    createPlace: "Cadastrar Local",
    noPlaceFound: "Nenhum Local encontrado",
    createAPlaceToBegin: "Crie um Local para começar",
    allDaysAlreadySelected: "Todos os dias ja foram selecionados",
    returnToListVehicles: "Retornar para todos",
    bestRoutePlanning: "Planejamento Melhor Rota",
    vehiclesGroups: "Grupos do Veículo",
    return: "Retornar",
    vehicleNotFound: "Veículo não encontrado",
    special: "Especial",
    boardingAddress: "Endereço de Emabarque",
    landingAddress: "Endereço de desemabarque",
    qrCodePassenger: "Qr Code Passageiro",
    downloadQrCode: "Download QR Code",
    errorWhenCreatingUser: "Encontramos problemas ao cadastrar este usuário",
    editFence: "Editar cerca",
    errorWhenLoadingRoute: "Encontramos problemas ao carregar a rota",
    errorWhenApplyingFilter: "Encontramos problemas ao aplicar o filtro",
    errorWhenCreatingDriver:
      "Encontramos problemas ao cadastrar este motorista",
    errorWhenSearchingForTerm: "Encontramos problemas ao buscar o termo",
    errorWhenRedirectingVehicleToMap:
      "Encontramos problemas ao ver o veículo no mapa",
    driverNotIdentified: "Não identificado",
    errorWhenAttachingImage: "Erro ao anexar a imagem",
    fuelRegisteredSuccessfully: "Abastecimento cadastrado com sucesso",
    showRoutes: "Mostrar rotas",
    centerVehicles: "Centralizar veículos",
    userData: "Dados do Usuário",
    passwordChangedSuccessfully: "A senha foi trocada com sucesso!",
    dateAndHour: "Data e Hora",
    currencyDecimalsUnits: "Moeda, Decimais e Unidades",
    shareRoute: "Compartilhar Rota",
    showTraffic: "Mostrar trânsito",
    hideTraffic: "Esconder trânsito",
    groupVehicles: "Agrupar veículos",
    ungroupVehicles: "Desagrupar veículos",
    hideNames: "Ocultar nomes",
    showNames: "Mostrar nomes",
    updateIn: "Atualização em",
    update: "Atualizar",
    identification: "Identificação",
    contactName: "Nome do Contato",
    externalId: "Id Externo",
    typeExternalId: "Digite o Id Externo",
    typeClientName: "Digite o Nome do Cliente",
    typeCompanyIdentification: "Digite o CNPJ/CPF",
    typePlaceIdentification: "Digite a identificação do local",
    typeCompanyName: "Digite a Razão Social",
    typeReasonToRefuseTheSolicitation: "Digite o motivo de recusa da solicitação",
    typeReasonToRefuseTheSolicitationPlaceholder: "Ex.: Carro indisponível",
    associatedClient: "Cliente associado",
    withCompanion: "Com acompanhante",
    companionData: "Dados de acompanhante",
    dataOfCompanion: "Dados do acompanhante",
    companionName: "Nome do acompanhante",
    typeCompanionName: "Digite o nome do acompanhante",
    companionPhone: "Telefone do acompanhante",
    typeCompanionPhone: "Digite o telefone do acompanhante",
    companionEmail: "Email do acompanhante",
    typeCompanionEmail: "Digite o email do acompanhante",
    typeContactName: "Digite o Nome do Contato",
    companyIdentification: "CNPJ/CPF",
    userDescription:
      "Usuários são as pessoas que tem acesso ao Contele Rastreador, pelo computador ou aplicativo.",
    clientsDescription:
      "Usuários são todas as pessoas que tem acesso ao sistema Contele Rastreador, tanto pelo computador quanto pelo aplicativo. Existem 03 tipos de acesso: Usuário, Administrador e Gestor.",
    knowMoreAboutUsers: "Saiba mais sobre as hierarquias...",
    selectAllVehicles: "Selecionar todos os veículos",
    selectAllClients: "Selecionar todos os clientes",
    selectAClient: "Selecione um cliente",
    selectACity: "Selecione uma cidade",
    selectADate: "Selecione uma data",
    noCityFound: "Nenhuma Cidade Encontrada",
    filterByGroup: "Filtre por grupos",
    seconds: "seg.",
    updating: "Atualizando",
    turnOn: "Ligado",
    turnOff: "Desligado",
    powerReconnected: "Reconectado",
    powerDisconnected: "Desconectado",
    vehicleTurnOn: "Veículo ligado",
    vehicleTurnOff: "Veículo desligado",
    vehicleNoSignal: "Área de sombra",
    vehicleNoSignalForMoreThen24Hours: "Área de sombra a mais de 24h",
    vehiclesTurnOn: "Veículos ligados",
    vehiclesTurnOff: "Veículos desligados",
    vehiclesNoSignal: "Área de sombra",
    vehiclesNoSignalForMoreThen24Hours: "Área de sombra a mais de 24h",
    consumptionPerVehicle: "Consumo por veículo",
    costsPerMonth: "Custo por mês",
		car: "Carro",
    idleCar: "Carro parado com motor ligado",
    speeding: "Excesso de velocidade",
    kmReached: "km Atingido",
    km: "km",
    kmTitle: "KM",
    documentation: "Documentação",
    documentations: "Documentações",
    mapVisualization: "Visualização no Mapa",
    notifications: "Notificações",
    vehicleData: "Dados do Veículo",
    eventsAndHoursOfUse: "Eventos e Horário de Utilização",
    loading: "Carregando",
    waitUntilLoadingEnds: "Aguarde até o fim do carregamento.",
    routesReport: "Relatório de Rotas",
    fuels: "Abastecimentos",
    fuel: "Abastecimento",
    fuelSupplieCadastre: "Cadastro de Abastecimento",
    checklist: "Checklists",
    routes: "Rotas",
    vehiclesStatus: "Status dos Veículos",
    vehicleStatus: "Status do Veículo",
		selectAStatus: "Selecione um Status",
    vehicleStatusDesc:
      "Veja sua frota de maneira completa. Últimas posições, Status e Irregularidades.",
    driverStatus: "Status do Motorista",
    events: "Eventos",
    audit: "Auditoria",
    drivers: "Motoristas",
    clients: "Clientes",
    client: "Cliente",
    places: "Locais",
    allStatus: "Todos os Status",
    place: "Local",
    clientsCreation: "Cadastro de Clientes",
    newPlace: "Novo Local",
    newClient: "Novo Cliente",
    createClient: "Cadastrar Cliente",
    clientsEdition: "Edição de Clientes",
    placesEdition: "Edição de Locais",
    driver: "Motorista",
    odometer: "Odômetro",
    literKMValue: "Valor por litro",
    motor: "Motor",
    document: "Documento",
    reachedKM: "KM Atingido",
    date: "Data",
    hour: "Hora",
    liters: "Litros",
    observation: "Observação",
    observations: "Observações",
    total_price: "Preço total",
    price: "Preço",
    file: "Anexo",
    gasoline: "Gasolina",
    ethanol: "Etanol",
    noConfiguration: "Sem Configuração Cadastrado",
    noDocumentation: "Nenhuma Documentação Cadastrada",
    gaz: "Gaz",
    biodiesel: "Biodiesel",
    eletric: "Elétrico",
    seePerRoute: "Ver por rota",
    seePerDay: "Ver por dia",
    diesel: "Diesel",
    gnv: "GNV",
    type: "Tipo",
    combustibleType: "Tipo de Combustível",
    veehicleType: "Tipo do veículo",
    vehicleSolicitations: "Solicitações de veículos",
    vehicleSolicitationsDesc: "Listagem das solicitações de retirada de veículos. Verifique, aprove ou reprove solicitações de retirada de veículos.",
    listSolicitations: "Lista de Solicitações",
    editVehicleSolicitations: "Editar Solicitações de veículos",
    solicitations: "Solicitações",
    requestingUser: "Usuário solicitante",
    solicitationDescriptionExample: "O veículo será utilizado para transportar entregas para empresa. Uma saveiro.",
    selectAnAvailableVehicle: "Selecione veículos para a solicitação",
    selectAnAvailableDrivers: "Selecione motoristas para a solicitação",
    periodOfUse: "Período de utilização",
    solicitationDescription: "Descrição solicitação",
    combustible: "Combustível",
    tank: "Tanque",
    complete: "Completo",
    partial: "Parcial",
    report: "Relatório",
    reports: "Relatórios",
    map: "Mapa",
    viewRoute: "Visualizar Rota",
    vehicles: "Veículos",
    vehiclesDesc:
      "Aqui você pode ver a listagem de Veículos, cadastrar novos, organizar a documentação, etc.",
    vehiclesEditDesc:
      "Preencha os dados do Veículo, que serão utilizados em Relatórios, Mapa, Eventos, etc.",
    vehicle: "Veículo",
		vehiclesInAll: "Veículos ao todo",
    command: "Comando",
    mapPlaceSearchPlaceholder: "Insira um endereço para encontrar o local",
    searchForAVehicles: "Busque por um veículo",
    selectAVehicle: "Selecione um veículo",
    searchVehicleOnMap: "Busque no mapa",
    selectAGroup: "Selecione um grupo",
    selectADriver: "Selecione um motorista",
    writeOdometer: "Digite o odômetro",
    writeTotalQuantity: "Digite a quantidade total",
    writeTotalPrice: "Digite o valor total",
    writePrice: "Digite o preço",
    writeObservation: "Digite suas obvervações aqui se necessário",
    filePlaceHolder: "Anexe aqui a foto do comprovante",
    group: "Grupo",
    drivingTime: "Tempo total de condução",
    groups: "Grupos",
    allGroups: "Todos os Grupos",
    fences: "Cercas Eletrônicas",
		CNHExpired: 'CNH Vencida',
    block: "Bloqueio",
    sendCommand: "Enviar Comando",
    blockCommand: "Bloquear",
    unblockCommand: "Desbloquear",
    productivity: "Produtividade",
    users: "Usuários",
    finance: "Financeiro",
    fencesEdition: "Edição de Cerca Eletrônica",
    vehiclesEdition: "Edição de Veículos",
    weeklySetupDescription:
      "Selecione os dias que irão receber a mesma configuração diária, escolha o Horário de Utilização e adicione mais períodos se necessário. Adicione outras configurações para os dias não selecionados anteriormente.",
    weeklySetup: "Configuração Semanal",
    dailySetupDescription:
      "Na Configuração Diária você pode configurar cada dia da semana, e separar por períodos dentro do dia clicando no botão de Mais (+). Para configurar, clique no dia desejado e escolha o Horário de Utilização.",
    dailySetup: "Configuração Diária",
    vehiclesEditHourOfUse: "Horário de Utilização",
    vehiclesEditHourOfUseSubtitle: "Edição de Veículos / Horário de Utilização",
    vehiclesEditHourOfUseDescription:
      "Determine os dias e horários que o Veiculo pode ser utilizado.",
    createNewFence: "Cadastrar nova cerca",
    createNewVehicle: "Cadastrar novo veículo",
    create: "Criar",
    printQRCode: "Imprimir QR Code",
    nameOfKmEvent: "Nome do evento de km atingido:",
    removeEvent: "Excluir Evento",
    addEvent: "Adicionar Evento",
    add: "Adicionar",
    odometerInUserUnit: (unit) => "Odômetro em " + unit,
    configNotifications: "Configurar Notificações",
    configOtherDays: "Configurar outros dias",
    previous: "Anterior",
    next: "Próximo",
    createFence: "Cadastrar Cerca",
    createVehicle: "Cadastrar Veículo",
    vehiclesCreation: "Cadastro de Veículos",
    fencesCreation: "Cadastro de Cercas",
    driverEdition: "Edição de Motorista",
    groupEdition: "Edição de Grupos",
    groupEditionDesc:
      "A separação dos Veículos por Grupos permite que você veja a posição deles no Mapa separadamente.",
    driversCreation: "Cadastro de Motoristas",
    groupsCreation: "Cadastro de Grupos",
    createDriver: "Cadastrar Motorista",
    createDriverDesc:
      "Cadastre, edite e envie mensagens (com segurança) para os Motoristas da sua frota.",
    createGroup: "Cadastrar Grupo",
    monday: "Segunda",
    tuesday: "Terça",
    wednesday: "Quarta",
    thursday: "Quinta",
    friday: "Sexta",
    saturday: "Sábado",
    sunday: "Domingo",
    name: "Nome",
    vehicleNameToShowInReports:
      "Nome do veículo que aparecerá no mapa e nos relatórios",
    vehicleNameToShowInReportsMessage: "A atualização dos dados do Veículo só será aplicada no mapa quando o Veículo receber pontos.",
    vehicleName: "Nome do veículo",
    page: "Página",
    author: "Autor",
    contract: "Contrato",
    vehicleModel: "Modelo do veículo",
    vehicleYear: "Ano do veículo",
    model: "Modelo",
    plateNumber: "Placa",
    vehicleTank: "Tanque",
    fillTheMaxCapacity: "Preencha a capacidade máxima em litros",
    fuelPrice: "Valor do Combustível",
    medianConsumptionOfFuel: "Consumo Médio de Combustível",
    medianConsumption: "Consumo Médio",
    odometerAdjustment: "Ajuste do Odômetro",
    odometerAdjustmentPerformed: "Ajuste realizado",
    odometerAdjustmentPerformedIn: "em",
    manufacturer: "Fabricante",
    manufacturerName: "Digite o fabricante do veículo",
		brand: "Marca",
    selectManufacturerYear: "Selecione o Ano de fabricação",
    moduleValidation: "Verificação de módulos",
    moduleAvaliableDescription: "Abaixo são os módulos disponíveis ainda não atribuidos a outros veículos.",
    selectVehicleHoursOfUsage: "Selecione o horário de utilização",
    yearManufacturer: "Ano de fabricação",
    module: "Módulo",
    avaliableModules: "Módulos disponíveis",
    unlinkModule: "Desvincular módulo atual",
    insertNameOfGroup: "Insira apenas o nome do grupo que deseja criar",
    registersLowerCase: "registros",
    emailLimit: "Você atingiu o limite de 20 emails.",
    invalidEmail: "Email Inválido",
    showOnMap: "Mostrar no Mapa",
    executed: "Executado",
    pendent: "Pendente",
    activated: "Ativado",
    scheduleReview: "Agendar revisão",
    changeOil:"Trocar óleo",
    alignAndBalance:"Alinhamento e balanceamento",
    changeWheels:"Trocar pneus",
    reviewBrakesAndSuspension:"Revisar freios e suspensão",
    removeTracker:"Retirar o rastreador para venda",
    initReportsStateTitle: "Selecione um período para gerar um relatório",
    initReportStateSubtitle: "Para gerar um relatório basta preencher os filtros acima e clicar no botão \"Gerar Relatório\".",
    noDeviceAttached: "Nenhum dispositivo vinculado",
    pinSuccess: "PIN copiado para área de transferência",
    seeOnMap: "Veja no Mapa",
    seeOnGoogleMaps: "Veja no Google Maps",
    accessVehicleDocumentation: "Acessar Documentação do Veículo",
    hello: "Olá ",
    noGroupsYet: "Você ainda não possui Grupos",
    toRegister: "para cadastrar",
    trackerPowerHas: "teve a alimentação de seu rastreador",
    andKnowHowToInstallModules: "e saiba como instalar seus Rastreadores.",
    distanceTraveledLessThan1: "Trajeto com distância percorrida inferior a 1",
    usageAchievements: {
      title: "Aproveitamento",
      subtitle: "Aproveitamento do sistema.",
      description: "Aumente o seu Aproveitamento dentro do sistema.",
      getTheBestOfConteleTracker: "Obtenha o melhor do Contele Rastreador.",
      followTheChecklist: "Siga o Checklist abaixo para aumentar o nível de Aproveitamento dentro do sistema.",
      emptyList: "Nenhum item encontrado !",
      checklist: "Checklist",
			items: "Itens",
      vehicleNotFound: "Nenhum Veículo encontrado !",
      checklistLeves: {
        begginer: "Nível iniciante",
        medium: "Nível médio",
        advanced: "Nível avançado"
      },
      checklistItems: {
        hasAllTrackersInstalled: {
          label: "Instalar todos os rastreadores",
          texts: {
            line1: "O 1º passo: Instalar rastreadores.",
            line2: "Instale todos os rastreadores nos veículos da frota."
          },
          helper: {
            link: "https://help.contelerastreador.com.br/pt-br/article/como-funciona-a-instalacao-do-contele-rastreador-1ueodqo/"
          }
        },
        allVehiclesSettingsCompleted: {
          label: "Cadastrar todos os dados de veículos da frota",
          texts: {
              line1: "Cadastrar dados dos veículos.",
              line2: "Cadastre todos os dados dos veículos da frota no sistema."
          },
          helper: {
            link: "https://help.contelerastreador.com.br/pt-br/article/como-cadastrar-os-veiculos-pbu8g6/"
          }
        },
        hasAppManagers: {
          label: "Instalar APP Contele Rastreador Gestores",
          texts: {
              line1: "Instalar APP Contele Rastreador.",
              line2: "Instale o APP Contele Rastreador no seu smartphone."
          },
          helper: {
            link: "https://help.contelerastreador.com.br/pt-br/article/aplicativo-para-android-e-ios-iphone-1z0mvy5/"
          }
        },
        allDriversHaveExpireDriverLicense: {
          label: "Cadastrar todos motoristas com vencimento na CNH",
          texts: {
              line1: "Aumente seu nível cadastrando todos seus motoristas.",
              line2: "A quantidade de Motoristas cadastrados precisa ser igual ou maior que a quantidade de veículos."
          },
          helper: {
              link: "https://help.contelerastreador.com.br/pt-br/article/como-cadastrar-informacoes-dos-motoristas-1ovtso9/",
          }
        },
        allVehiclesHaveDriver: {
          label: "Identificar quem está dirigindo o veículo",
          texts: {
              line1: "De olho no volante.",
              line2: "Identifique o motorista que está na direção do veículo."
          },
          helper: {
            link: "https://help.contelerastreador.com.br/pt-br/article/as-formas-de-identificacao-do-motorista-1a5jgbm/"
          }
        },
        allVehiclesHaveSpeedEvent: {
          label: "Cadastrar Velocidade Máxima para todos os Veículos",
          texts: {
              line1: "Aumente seu nível configurando uma Velocidade Máxima para todos seus Veículos.",
              line2: "Você sabe o que fazer com as informações de velocidade excedida?",
          },
          helper: {
              link: "https://help.contelerastreador.com.br/pt-br/article/velocidade-excedida-149td5r/",
          }
        },
        allVehiclesHaveOdometer: {
          label: "Cadastrar todos os Odômetros",
          texts: {
              line1: "Aumente seu nível configurando todos os Odômetros em seus Veículos.",
              line2: "Você sabe para que serve e como configurar os Odômetros de sua frota?"
          },
          helper: {
              link: "https://help.contelerastreador.com.br/pt-br/article/como-alterar-a-configuracao-do-odometro-barugh/",
          }
        },
        allVehiclesHaveIdleEvent: {
          label: "Cadastrar Tempo máximo do Veículo parado com motor ligado",
          texts: {
              line1: "Aumente seu nível cadastrando um tempo máximo para Veículo parado com motor ligado.",
              line2: "Você sabe para que serve o recurso de tempo de parada excedido?"
          },
          helper: {
              link: "https://help.contelerastreador.com.br/pt-br/article/o-que-e-tempo-de-parada-excedido-1tj53td",
          }
        },
        allVehiclesHaveSchedule: {
          label: "Configurar Dia e Horário permitido para utilização de todos os Veículos",
          texts: {
              line1: "Aumente seu nível configurando dia e hora de utilização em todos seus Veículos.",
              line2: "O que é, qual é a importância, como utilizar e analisar?"
          },
          helper: {
              link: "https://help.contelerastreador.com.br/pt-br/article/eventos-e-horarios-de-utilizacao-do-veiculo-3gvvjb/",
          }
        },
        allVehiclesHaveKmEvent: {
          label: "Configurar ao menos um Evento de KM Atingido por Veículo",
          texts: {
              line1: "Aumente seu nível configurando um Evento de KM para cada um de seus Veículos.",
              line2: "Como ele você pode cadastrar eventos como: troca de óleo, revisão completa, alinhamento, entre outros dados.",
          },
          helper: {
              link: "https://help.contelerastreador.com.br/pt-br/article/km-atingido-o-que-e-e-para-que-serve-esse-recurso-yzcqtp/",
          }
        },
        hasFences: {
          label: "Criar ao menos uma Cerca Eletrônica",
          texts: {
              line1: "Aumente seu nível criando ao menos uma Cerca Eletrônica.",
              line2: "Você sabe para que serve e como utilizar a cerca eletrônica?"
          },
          helper: {
              link: "https://help.contelerastreador.com.br/pt-br/article/cerca-eletronica-xl6b26/",
          }
        },
        allVehiclesHaveDocs: {
          label: "Enviar ao menos um documento por Veículo",
          texts: {
              line1: "Aumente seu nível cadastrando pelo menos um Documento em seus Veículos.",
              line2: "Crie e organize pastas na nuvem com o Google Drive e o Contele Rastreador.",
          },
          helper: {
              link: "https://help.contelerastreador.com.br/pt-br/article/saiba-como-organizar-a-documentacao-da-sua-frota-q2ajaf/",
          }
        },
        hasFrequentlyRegisteredFuelSupplies: {
          label: "Registrar com frequência os abastecimentos de todos os Veículos",
          texts: {
              line1: "Aumente seu nível registrando frequentemente os Abastecimentos.",
              line2: "Abastecimentos: O que é, qual é a importância, como utilizar e analisar?"
          },
          helper: {
              link: "https://help.contelerastreador.com.br/pt-br/article/abastecimentos-fodz9j/",
          }
        },
        hasFrequentlyRegisteredChecklists: {
          label: "Registrar com frequência o Checklist de todos os Veículos",
          texts: {
              line1: "Aumente seu nível registrando frequentemente os Checklists.",
              line2: "Checklist: O que é, qual é a importância, como utilizar e analisar?"
          },
          helper: {
              link: "https://help.contelerastreador.com.br/pt-br/article/checklist-do-veiculo-1iwutx/",
          }
        },
      }
    },
    tooltipHelpTexts: {
      grupos: {
        messageLink: "O nome do grupo não pode ser separado por espaço."
      },
      vehicleNameToShowInReportsTooltip: {
        text: "O Nome do veículo só será atualizado no mapa quando o mesmo receber novos pontos. Veículos desligados não receberão atualização até serem ligados novamente.",
      },
      noSignal: {
        text: 'Esse Status aparecerá quando o rastreador estiver na área de sombra da operadora, portanto ele está armazenando dados e transmitirá sozinho assim que voltar para área com cobertura.',
        link: 'https://help.contelerastreador.com.br/pt-br/article/status-dos-veiculos-ligado-desligado-e-sem-sinal-67hmpc/'
      },
      vehiclesWithoutCommunication: {
        text: 'Esse Status aparecerá se o veículo ficar mais de 24h sem transmitir dados ao sistema por estar em área de sombra.',
        link: 'https://help.contelerastreador.com.br/pt-br/article/status-dos-veiculos-ligado-desligado-sem-sinal-e-mais-67hmpc/'
      },
      noCommunication: {
        text: 'Veículos há mais de 3 dias úteis sem comunicação com nossos servidores. Verifique se esse veículo está sendo utilizado e em área aberta com cobertura da Operadora. Caso esteja sem uso ou em manutenção, edite o estágio do veículo dentro do sistema.',
		link: 'https://help.contelerastreador.com.br/pt-br/article/status-dos-veiculos-ligado-desligado-sem-sinal-e-mais-67hmpc/'
      },
      noUse: {
        text: 'Veículos em manutenção ou sem uso alterado pelo Gestor. Veja como mudar o estágio do veículo.',
		link: 'https://help.contelerastreador.com.br/pt-br/article/status-dos-veiculos-ligado-desligado-sem-sinal-e-mais-67hmpc/'
      },
      noModules: {
        text: 'Rastreadores disponíveis (ativos) que ainda não foram instalados. Veja como instalar e testar.',
		link: 'https://help.contelerastreador.com.br/pt-br/article/status-dos-veiculos-ligado-desligado-sem-sinal-e-mais-67hmpc/'
      },
      drivers: {
        codeId: {
          text:
            "Caso a sua empresa tenha uma matrícula do funcionário ou algo semelhante, utilize o Código de Identificação para isso.",
          linkText: "Saiba mais.",
          link: "https://help.contelerastreador.com.br/pt-br/article/como-cadastrar-informacoes-dos-motoristas-1ovtso9/",
        },
        expireDriverLicenseDate: {
          text:
            "Cadastre a Data de Vencimento da CNH do Motorista. Você será avisado 30 dias antes do vencimento, evitando transtornos maiores como multas e apreensão do Veículo.",
          textEdit:
            "Evite multas. Cadastre e seja avisado antes do vencimento.",
          linkText: "Saiba mais.",
          link: "https://help.contelerastreador.com.br/pt-br/article/1ovtso9/",
        },
        driverTel: {
          text:
            "Cadastre um número de WhatsApp, que você poderá contatar o Motorista com facilidade, e até enviar rotas.",
          linkText: "Saiba mais.",
          link: "https://help.contelerastreador.com.br/pt-br/article/envie-um-whatsapp-para-seus-motoristas-pelo-contele-rastreador-1amxsqc/",
          textAfterlink:
            "Atenção: Não converse com o Motorista enquanto ele está dirigindo. Evite por em risco a vida dele e de outras pessoas.",
        },
        routesTotalCost: {
          text: "O Valor que o sistema mostra é um valor estimado e baseado na configuração do Veículo.",
          link: "https://help.contelerastreador.com.br/pt-br/article/valor-estimado-do-gasto-com-combustivel-1t82ciy/"
        },
        licenceDateExpireTable:
          "Vencimento não cadastrado",
      },
      vehicleMaxSpeedAllowed: {
        text:
          "O Evento de Excesso de Velocidade registra quando o Veículo ultrapassa uma determinada velocidade. Quando isso acontecer, você receberá uma notificação no App e E-mail.",
        link:
          "https://help.contelerastreador.com.br/pt-br/article/velocidade-excedida-149td5r/",
      },
      vehicleHourOfUse: {
        text: `O Evento de Uso fora do Horário de Utilização registra sempre que o Veículo é utilizado fora dos horários e dias permitidos configurados.
          Quando isso acontecer, você receberá uma  Notificação no APP e E-mail.`,
        link:
          "https://help.contelerastreador.com.br/pt-br/article/horario-de-utilizacao-do-veiculo-3gvvjb/",
      },
      consumptionMonth: {
        text: (distanceUnit, volumetricUnit) =>
          `A Média de consumo de combustível (${distanceUnit}/${volumetricUnit}) das Colunas apresentadas, considerando o período selecionado.`,
        link:
          "https://help.contelerastreador.com.br/pt-br/article/abastecimentos-fodz9j/",
      },
      unidentifiedDriver: {
        text:
          "O Evento de Motorista Não Identificado registra sempre que um Veículo é conduzido sem um Motorista se identificar. Quando isso acontecer, você receberá uma  Notificação no APP e E-mail.",
        link:
          "https://help.contelerastreador.com.br/pt-br/article/evento-de-motorista-nao-identificado-b76nvp/",
      },
      vehicleIdle: {
        text:
          "O Evento de Carro parado com o motor ligado registra quando um Veículo fica ligado e parado mais tempo que o permitido na configuração. Quando isso acontecer, você receberá uma  Notificação no APP e E-mail.",
        linkText: "Para que serve o recurso de tempo de parada excedido?",
        link:
          "https://help.contelerastreador.com.br/pt-br/article/o-que-e-tempo-de-parada-excedido-1tj53td/s",
      },
      vehicleDocumentation: {
        text:
          "Crie e organize pastas na nuvem com o Google Drive e o Contele Rastreador.",
        linkText: "Saiba mais.",
        link:
          "https://help.contelerastreador.com.br/pt-br/article/saiba-como-organizar-a-documentacao-da-sua-frota-q2ajaf/",
      },
      vehicleGroupMapVisualization: {
        text:
          "A visualização por Grupos permite que você veja a posição dos Veículos no Mapa separadamente.",
        linkText: "Saiba mais.",
        link:
          "https://help.contelerastreador.com.br/pt-br/article/grupos-de-veiculos-u8o9yz/",
      },
      vehicleType: {
        text:
          "Utilize o Tipo de Veículo para categorizar os modelos dos Veículos cadastrados.",
      },
      vehicleActiveDevice: {
        text:
          "Último aparelho utilizado para acessar o aplicativo Contele Driver",
      },
      vehicleKmReached: {
        text:
          "O Evento de km Atingido é um recurso utilizado para ajudar na gestão da manutenção dos veículos. Ao ultrapassar o Odômetro configurado, você receberá uma notificação no App e E-mail.",
        linkText: "km Atingido: O que é e para que serve esse recurso",
        link:
          "https://help.contelerastreador.com.br/pt-br/article/km-atingido-o-que-e-e-para-que-serve-esse-recurso-yzcqtp/?1584653313035",
      },
      vehicleGeoFence: {
        text: `O Evento de Cerca Eletrônica registra sempre que o Veículo saí de uma área configurada.
          Quando isso acontecer, você receberá uma  Notificação no APP e E-mail. Saiba mais.`,
        linkText:
          "Você sabe para que serve e como utilizar a Cerca Eletrônica?",
        link:
          "https://help.contelerastreador.com.br/pt-br/article/cerca-eletronica-xl6b26/",
      },
      vehicleStatus: {
        text:
          "Aqui você pode verificar o Estado dos Veículos.",
        link:
          "https://help.contelerastreador.com.br/pt-br/article/o-que-e-o-estado-ativado-e-desativado-do-veiculo-1d6utbc/",
      },
      vehiclePIN: {
        text:
          "O PIN é um código de identificação único e exclusivo do Veículo, permitindo o acesso ao APP Contele Driver (Aplicativo do Motorista).",
        link:
          "https://help.contelerastreador.com.br/pt-br/article/aplicativo-do-motorista-app-contele-driver-mtdbwa/",
      },
      vehicleFuelPrice: {
        text:
          "O Valor do Combustível é utilizado para mostrar o gasto estimado em Relatórios e Rotas.",
        link:
          "https://help.contelerastreador.com.br/pt-br/article/valor-estimado-do-gasto-com-combustivel-1t82ciy/s",
      },
      vehicleOdometerAdjustment: {
        text: `Preencha o Odômetro do Veículo aqui, colocando exatamente o que está no Painel.
        Após a realização de rotas, o Odômetro do sistema pode ter uma pequena diferença com o do Veículo.`,
        link:
          "https://help.contelerastreador.com.br/pt-br/article/como-alterar-a-configuracao-do-odometro-barugh/",
      },
      vehicleOdometerCreate: {
        text: `O Odômetro só pode ser editado após a finalização do cadastro do Veículo.
        Após salvar esse Veículo, clique em Edição de Veículo. Toda alteração no Odômetro só é efetivamente atualizada após o Veículo ser ligado.`,
        link:
          "https://help.contelerastreador.com.br/pt-br/article/como-alterar-a-configuracao-do-odometro-barugh/",
      },
      vehicleMedianConsumption: {
        text:
          "Cadastre o consumo médio, em litros, por km percorrido. Junto com o Valor do Combustível, essa informação é utilizada para mostrar um custo estimado de combustível do Veículo.",
        link:
          "https://help.contelerastreador.com.br/pt-br/article/valor-estimado-do-gasto-com-combustivel-1t82ciy/",
      },
      hierarchy: {
        text: "Existem 5 níveis de acesso: Usuário, Usuário com Permissões, Administrativo, Gestor e Visualizador.",
        link:
          "https://help.contelerastreador.com.br/pt-br/article/usuarios-f44fyz/#1-hierarquias-de-acesso-ao-sistema",
      },
			group: {
				text: "Selecione um ou mais grupos de veículos para esse usuário.",
				link:
					"https://help.contelerastreador.com.br/pt-br/article/grupos-de-veiculos-u8o9yz/"
			},
      phone: {
        text: "Telefone do Usuário. O preenchimento desse campo permite a integração com o Whatsapp.",
        link:
          "https://help.contelerastreador.com.br/pt-br/article/envie-um-whatsapp-para-seus-motoristas-pelo-contele-rastreador-1amxsqc/",
      },
      endDate: {
        text:
          "Essa é a data de vencimento da sua fatura. Caso deseje alterar, entre em contato pelo Chat. Saiba mais sobre",
        linkText: "Faturas e Boletos",
        link:
          "https://help.contelerastreador.com.br/pt-br/article/como-faco-para-visualizar-as-faturasboletos-9zsbez/",
      },
      drivingTime: {
        text:
          "O Tempo Total de Condução é calculado pelo tempo que o Veículo ficou ligado e em movimento, considerando o filtro de Período selecionado.",
      },
      totalDistance: {
        text:
          "Distância Total em km (quilômetros) percorrida pelo Veículo, considerando o filtro de Período selecionado.",
      },
      cost: {
        text:
          "O Custo Total é um valor estimado, e calculado baseado no custo de combustivel que você mesmo configurou, considerando o Período selecionado.",
        linkText: "Saiba mais.",
        link:
          "https://help.contelerastreador.com.br/pt-br/article/valor-estimado-do-gasto-com-combustivel-1t82ciy/",
      },
      hasOdometerCommandInKmReport: {
        text:
          "Houve uma alteração de odômetro para este veículo no período selecionado, mas o sistema considerou a diferença e calculou a distância corretamente",
      },
      estimatedCost: {
        text:
          "O Custo Estimado de Combustível é baseado no custo do litro de combustível e de média de consumo configurados no Cadastro do Veículo.",
        linkText: "Saiba mais.",
        link:
          "https://help.contelerastreador.com.br/pt-br/article/valor-estimado-do-gasto-com-combustivel-1t82ciy/",
      },
      liters: {
        text:
          "Essa é a Quantidade total de Litros do Abastecimento. O registro deve sempre respeitar as 3 casas após a virgula.",
        linkText: "Saiba mais.",
        link:
          "https://help.contelerastreador.com.br/pt-br/article/abastecimentos-fodz9j/#1-como-registrar-os-abastecimentos",
      },
      odometer: {
        text:
          "O Odômetro do Contele Rastreador pode ter uma pequena diferença comparado com o do Veículo.",
        linkText: "Saiba mais.",
        link:
          "https://help.contelerastreador.com.br/pt-br/article/por-que-o-odometro-do-veiculo-tem-diferenca-com-do-sistema-e90zz3/",
      },
      fully_filled: {
        text:
          "O Abastecimento pode ter sido Completo (Tanque Cheio) ou Parcial. Dica de produtividade: Oriente os seus Motoristas a sempre abastecerem o Tanque Cheio.",
      },
      average_km_liter: {
        text:
          "A Média Real é o Consumo de combustível (km/l), considerando o Odômetro do Abastecimento anterior.",
        linkText: "Saiba mais.",
        link:
          "https://help.contelerastreador.com.br/pt-br/article/abastecimentos-fodz9j/?1584653859671",
      },
      fenceSpeedLimit: {
        text:
          "Configure uma Velocidade Máxima que os Veículos podem andar dentro dessa região da Cerca. Quando o Veículo exceder esse limite na região, você receberá uma notificação no App e E-mail.",
        link:
          "https://help.contelerastreador.com.br/pt-br/article/cerca-eletronica-xl6b26/#1-como-criar-uma-cerca-eletronica",
      },
      fenceShowOnMap: {
        text:
          "Ative ou Desative a exibição das Cercas Eletrônicas nos Mapas do sistema. Tal função pode lhe ajudar a identificar com facilidade regiões importantes.",
        link:
          "https://help.contelerastreador.com.br/pt-br/article/cerca-eletronica-xl6b26/#1-como-ativardesativar-cercas-eletronicas-e-mostrar-no-mapa",
      },
      vehicleStatusDesconected : {
        text: "O Evento de Desconectado da alimentação principal registra sempre que um Módulo é desconectado da alimentação do Veículo. Quando isso acontecer, você receberá uma  Notificação no APP e E-mail. Saiba mais.",
        link: "https://help.contelerastreador.com.br/pt-br/article/1cagk1t"
      },
      vehicleStatusReportAutoRefresh: {
        text: "Veja sua frota de maneira completa. Últimas posições, Status e Irregularidades.",
        link: "https://help.contelerastreador.com.br/pt-br/article/relatorio-de-status-dos-veiculos-1mknmv2/",
      },
      sensor: {
        text: "Receba notificações dos Eventos de Sensores do rastreador, como uma porta aberta ou pisca alerta ligado. Obs: Este Evento funcionará apenas em rastreadores configurados para isso.",
        link: "https://help.contelerastreador.com.br/pt-br/article/como-configurar-os-sensores-no-sistema-uj092o/",
      }
    },
    desactivated: "Desativado",
    modifiedDate: "Data de Modificação",
    createdDate: "Data de Criação",
    actions: "Ações",
    reload: "Recarregar",
    seePlace: "Ver no mapa",
    idAndName: "ID - Nome",
    noGeoFenceFound: "Nenhuma cerca eletrônica encontrada",
    noVehicleFound: "Nenhum veículo encontrado",
    noUsersFound: "Nenhum usuário encontrado",
    noSolicitationFound: "Nenhuma solicitação encontrada",
    noOrganizationFound: "Nenhuma organização encontrada",
    geoFenceDescription:
      "Essa é uma função que registra quando o Veículo entra ou sai de uma área que foi determinada por você.",
    geoFenceHelpLinkText:
      "Cerca Eletrônica: Como funciona, para que serve e como utilizar",
    geoFences: "Cercas Eletrônicas",
    geoFence: "Cercas Eletrônica",
    hoursOfUse: "Horário de utilização",
    hoursOfUseOut: "Uso fora do Horário de utilização",
    createKmEventDescription:
      "Crie eventos para serem registrados quando este veículo atingir o odômetro configurado.",
    selectDaysAndHoursOfUsage:
      "Selecione os dias e horários que os veículos poderão ser utilizados.",
    googleDriveIntegration:
      "Faça a integração de uma pasta no Google Drive com os documentos de sua frota e mantenha-se organizado.",
    editHoursOfUse: "Editar Horários de Utilização",
    appFullName: "Aplicativo do Gestor",
    installAppForReceiveNotifications:
      "Baixe o aplicativo para receber notificações de eventos e tenha acesso à diversos relatórios de produtividade.",
    installAppIn: "Baixe o APP na",
    installAppInPlayStore: "Play Store (Android)",
    installAppOrIn: "ou na",
    installAppInAppStore: "App Store (iOS)",
    pleaseTryAgain: "Por favor, tente novamente",
    clickingHere: "clicando aqui",
    sendNewCommandToBegin: "Envie um comando começar",
    createNewFenceToBegin: "Cadastre uma cerca para começar",
    createNewUserToBegin: "Cadastre um usuário para começar",
    createASolicitationToBegin: "Cadastre uma solicitação para começar",
    manage: "Gerenciar",
    showing: "Exibindo de ",
    until: "Até",
    from: "De",
    downloadOurApp: "Baixe nosso APP:",
    downloadDriverAppFullText: "Faça o Download do app Contele Driver para utilizar em sua rotina nos respectivos links",
    downloadDriverAppFullTextOneLink: "Baixe o app Contele Driver no link:",
    phoneMask: "+55 (00) 00000-0000",
    driverLicenseMask: "00000000000",
    companyIdentificationMask: "00.000.000/0000-00",
    userIdentificationMask: "000.000.000-00",
    userIdentificationMaskWithExtraZero: "000.000.000-000",
    zipcodeMask: "00000-000",
    minimoneyMask: "000.000.000.000.000,00",
    plateMask: "SSS-0A00",
    dateTimeMask: "dd/MM/yyyy hh:mm",
    dateMask: "dd/MM/yyyy",
    hourMask: "hh:mm:ss",
    cancel: "Cancelar",
    continue: "Continuar",
    save: "Salvar",
    nickname: "Apelido",
    nameOfDriver: "Nome do Motorista",
    nameOfGroup: "Nome do Grupo",
    nicknamePlaceholderInput:
      "Nome que aparecerá nos mapas, relatórios, etc...",
    phone: "Telefone",
    phonePlaceholder: "DDD + Telefone do Usuário",
    hierarchy: "Nível de Acesso",
    userDefaultPassword: (password) =>
      "A senha padrão desse usuário é: " + password + ".",
    userShowInformation:
      " Após o login no sistema, ele poderá mudá-la. Saiba mais em Como alterar minha senha?",
    codeId: "Código de identificação",
    codeIdPlaceholder: "Digite um código para identificação do motorista",
    driverLicenseNumber: "Número da CNH",
    driverLicenseNumberPlaceholder: "Digite a CNH do motorista",
    expireDriverLicense: "Vencimento der CNH",
    expireDriverLicenseDate: "Data de vencimento da CNH",
    expireDriverLicensePlaceholder:
      "Digite a data de vencimento da CNH do motorista",
    keyId: "ID da Chave",
    keyIdPlaceholder: "Digite o ID da chave (não digitar os 4 primeiros zeros)",
    statusCode: "Chave de acesso",
    status: "Status",
    vehiclesQty: "Quantidade de Veículos",
    creationDate: "Data do Cadastro",
		all: "Todos",
    departureDate: "Data de saída",
    lastUpdated: "Última Atualização",
    lastAccess: "Último login em:",
    deviceActive: "Aparelho Ativo",
    versionApp: "Versão APP",
    lastDevice: "Aparelho Anterior",
    active: "Ativo",
    inactive: "Inativo",
    activateUser: "Ativar Usuário",
    activateDriver: "Ativar Motorista",
		toActive:"Ativar",
    noDriverFound: "Nenhum Motorista encontrado",
    noClientFound: "Nenhum Cliente encontrado",
    noGroupFound: "Nenhum grupo encontrado",
    showOnlyActiveDrivers: "Mostrar somente Motoristas ativos",
    showOnlyActiveUsers: "Mostrar somente Usuários ativos",
    showOnlyActiveFences: "Mostrar somente Cercas ativos",
    showOnlyActiveVehicles: "Mostrar somente Veículos ativos",
    showOnlyActiveClients: "Mostrar somente Clientes ativos",
    showOnlyActivePlaces: "Mostrar somente Locais ativos",
    showOnlyActiveSolicitations: "Mostrar somente Solicitações ativas",
    createAGroupToBegin: "Cadastre um grupo para começar",
    createADriverToBegin: "Cadastre um motorista para começar",
    speedLimitText: "Velocidade máxima dentro da Cerca",
    associatedVehicles: "Veículos Associados",
    associatedVehicle: "Veículo Associado",
    associatedDriver: "Motorista Associado",
    associateVehiclesToGroup: "Clique no campo abaixo para associar os veículos",
    associateVehicles: "Associar Veículos",
    associateDrivers: "Associar Motoristas",
    clickInsideMapToDrawFence:
      "Clique no mapa para desenhar sua cerca. Você pode desfazer com o botão direito do mouse.",
    pin: "PIN",
    yourAccount: "Seu Acesso",
    Admin: "Admin",
    routeFromDay: "Rota do dia:",
    yourCompany: "Sua Empresa",
    leave: "Sair",
    filter: "Buscar pelos itens listados",
    groupsDescription:
      "A separação dos Veículos por Grupos permite que você veja a posição deles no Mapa separadamente.",
    createUser: "Cadastrar Usuário",
    userCreation: "Cadastro de Usuários",
    typeUser: "Hierarquia",
    email: "E-mail",
    typeYourRegisteredEmail: "Digite e-mail cadastrado",
    emails: "E-mail(s)",
    toInsertaEmail: "Para inserir mais de um, separe por vírgula.",
    fillWithYourEmail: "Preencha com o(s) seu(s) e-mail(s)",
    typeEmail: "Digite o email",
    developedByFullText: () =>
      "Desenvolvido pela Contele Rastreadores  -  Todos os direitos reservados " +
      new Date().getFullYear(),
    access: "Accessar",
    typeEmailExample: "Ex.: maria@email.com",
    typeYourEmail: "Digite seu e-mail",
    typeZipcode: "Digite o CEP",
    typeObservation: "Digite aqui uma observação",
    password: "Senha",
    redefineYourPassword: "Redefina sua senha",
    redefine: "Redefinir",
    passwordRepeat: "Confirmação da Senha",
    typePassword: "Digite a senha",
    fieldRequired: "Campo obrigatório",
    fillRequired: "Campos obrigatórios não preenchidos.",
    fillMarkedInRed: "Preencha os campos marcados em vermelho.",
    fieldFormatRequired: "Campo não está no formato correto",
    emailPasswordWrong: "Email ou senha incorretos",
    passwordError: "Problemas ao salvar nova senha",
    passwordWrong: "As duas senhas estão diferentes",
    fullfillPasswords: "Preencha a senha e a confirmação",
    allowedVehicles: "Veículos Permitidos",
    allowedClients: "Clientes Permitidos",
    commandBlock: "Bloqueio",
    commandBlockDesc:
      "Você poderá Bloquear ou Desbloquear um Veículo pelo computador ou pelo aplicativo. Use esse recurso com cautela.",
    commandHistory: "Histórico",
    noCommandsFound: "Nenhum Comando encontrado",
    listUsers: "Lista de Usuários",
    editUser: "Editar Usuário",
    productDescription:
      "Solução inteligente para o aumento de produtividade e redução de custos da sua frota.",
    welcomeToVehicleSolicitation:
      "Bem-vindo ao seu painel de solicitação de veículos.",
    vehicleSolicitationDescription:
      "Aqui você pode fazer solicitações de veículos e reservar o melhor horários de  forma rápida e prática.",
    editVehicles: "Editar Veículos",
    editOdometerMessage: "Uma nova configuração de Odômetro só refletirá no sistema após o Veículo ser ligado e enviar sinal. Os relatórios anteriores a essa alteração, permanecerão com os valores antigos.",
    settings: "Configurações da Empresa",
    ClickHere: "Clique aqui",
    clickHereToCreateANewGroup: "Adicionar Grupo",
    questions: "Dúvidas?",
    inCaseOfDoubts: "Dúvidas? Consulte sempre a ",
    orSendAChatMessage: " ou envie uma mensagem no Chat do Sistema.",
    numberCenter: "0800 031 7112",
    numberCenterLink: "tel:08000317112",
    knowServicesLink: "https://help.contelerastreador.com.br/pt-br/",
    suportEmail: "suporte@contelerastreador.com.br",
    welcome: "Olá, seja bem-vindo",
    welcomeMenu: "Bem-vindo",
    passwordRecovery: "Recuperando sua senha",
    typeNewPassword: "Digite abaixo sua senha nova.",
    newPassword: "Senha nova",
    confirmYourNewPassword: "Confirmar senha nova",
    rememberedOldPassword: "Lembrou sua senha?",
    toLogin: "para fazer login.",
    forgotYourPassowordTitle: "Esqueceu sua senha?",
    forgotMyPassoword: "Esqueci minha senha",
    forgotYourPassowordDescription:
      "Digite seu e-mail cadastrado abaixo e enviaremos um link para recuperação de sua senha.",
    enter: "Entrar",
    hireNow: "Faça seu Cadastro",
    hireNowMessage: "Ainda não possui uma conta?",
    logInBelow: "Gestão de Frotas e Rastreamento Veicular",
    forgottenPassword: "caso tenha esquecido sua senha.",
    selectAItem: "Selecione um item",
    companyName: "Razão Social",
    tradingName: "Nome Fantasia",
    lastRecord: "Último registro",
    vehicleStage: "Estágio do Veículo",
    selectAStage: "Selecione um Estágio",
    addressSingular: "Endereço atual",
    addresses: "Endereços",
    address: "Logradouro",
    fullAddress: "Endereço",
    accessCode: "Chave de Acesso",
    typeAccessCode: "Digite a Chave de Acesso",
    typeAddress: "Digite o endereço",
    typePhone: "Digite o telefone",
    typeNeighborhood: "Digite o bairro",
    typeNumber: "Digite o número",
    typeComplement: "Digite o complemento",
    complement: "Complemento",
    number: "Número",
    city: "Cidade",
    state: "Estado",
    neighborhood: "Bairro",
    zipcode: "CEP",
    DataAndSettings: "Dados e Configurações",
    cNPJCPF: "CNPJ/CPF",
    currency: "Moeda",
    previousActiveDevice: "Aparelho anterior",
    activeDevice: "Aparelho ativo",
    iconColor: "Cor do Ícone",
    vehicleColor: "Cor do Veículo",
    backgroundColor: "Cor de Fundo",
    app: "APP",
    vehicleTypeOnMap: "Ícone para aparecer no mapa",
    vehicleOdometerExample: "345",
    vehicleMedianPriceConsumptionExample: "5",
    vehicleLitersPriceExample: (decimalSeparator = ',') => `5${decimalSeparator}00`,
    vehicleTankExample: "Ex.: 55, 60, 70 litros.",
    vehicleModelExample: "Ex.: Celta, Gol, Corsa, etc...",
    vehiclePlateExample: "Ex.: ABC-1234",
    selectTheDefaultDriver: "Selecione o motorista padrão",
    fuelType: "Tipo do combustível",
    selectFuelType: "Selecione o tipo de combustível",
    typeTheModel: "Digite o modelo",
    vehicleType: "Tipo do veículo",
    selectVehicleType: "Selecione o tipo do veículo",
    selectYear: "Selecione o ano",
    country: "País",
    useBillingAddressSame:
      "Utilizar o mesmo Endereço de Entrega como Endereço de Cobrança",
    language: "Idioma",
    dateFormat: "Formato de data",
    groupFilter: "Grupo para filtro de visualização no mapa",
    documentationUrl:
      "Digite ou cole abaixo o link de sua pasta no Google Drive",
    documentationUrlHelp:
      "Acesse nosso tutorial para aprender como montar suas pastas",
    searchHelp: "A busca será feita somente nos itens desta página. Utilize o filtro de paginação ao final deste menu, para exibir mais resultados na página.",
    documentationUrlExample: "Ex.: https://drive.google.com/drive/my-drive",
    maxSpeedAllowed: "Velocidade máxima permitida",
    maxSpeedAllowedExample: "30",
    maxTimeStoppedMinified: "T. Máximo Parado",
    maxTimeStoppedWithTheEngineOn:
      "Tempo máximo do veículo parado com motor ligado (minutos)",
    maxTimeStoppedExample: "5",
    timeFormat: "Formato de tempo",
    timezone: "Fuso horário",
    decimalSeparators: "Separador de decimais",
    thousandSeparators: "Separador de milhar",
    distanceUnit: "Unidade de distância",
    volumetricUnit: "Unidade Volumétrica",
    registersFuelSupplies: "Relatórios - Registros dos Abastecimentos",
    registersFuelSuppliesDesc:
      "Esse relatório apresenta os registros de cada abastecimento do Veículo, seja pelo Motorista ou Usuário responsável.",
    quantity: "Quantidade",
    value: "Valor",
    mCadastred: "M. Cadastrada",
    realAverage: "Média real",
    noFuelSupplieRegisterFound: "Nenhum registro de abastecimento encontrado",
    noFuelSupplieFound: "Nenhum abastecimento encontrado",
    createSupplie: "Cadastrar Abastecimento",
    selectPeriod: "Selecione o período",
    generateReport: "Gerar relatório",
    month: "Mês",
    priceUnit: "R$",
    averageCostPerLiter: "Valor médio",
    monthCostFuelSuppliesDesc:
      "Esse relatório mostra o total de custo e quantidade de litros abastecidos por mês para todos os Veículos da frota.",
    monthCostFuelSupplies: "Relatório - Custo médio de combustível por mês",
    noMonthCostFound: "Nenhum custo médio encontrado",
    createAFuelSupply: "Crie um abastecimento para começar",
    searchByKey: "Buscar por palavra-chave",
    averageConsumptionPerMonth:
      "Relatório - Consumo médio de combustível por veículo",
    averageConsumptionPerMonthDesc: (distanceUnit, volumetricUnit) =>
      `Esse relatório mostra o consumo médio (${distanceUnit}/${volumetricUnit}) mensal por Veículo.`,
    average: "Média",
    noAverageConsumptionFound: "Nenhum consumo médio encontrado",
    checklistReport: "Relatório - Registros de Checklists",
    checklistReportDesc:
      "Esse relatório apresenta os registros de Checklists dos Veículos efetuados, considerando o período selecionado.",
    createAChecklistToBegin: "Crie um checklist para começar",
    noRoutesReportFound: "Nenhuma rota encontrada",
    createARoute: "Crie uma rota para começar",
    noChecklistsFound: "Nenhum checklist encontrado",
    noKmFound: "Nenhuma distância percorrida encontrada",
    noVehicleStatusFound: "Nenhum status de veículo encontrado",
    noKmRegisterFound: "Nenhum registro de distância percorrida encontrada",
    noCheckListRegisterFound: "Nenhum registro de checklist encontrado",
    selectAEvent: "Selecione um evento",
    daysS: "dia(s)",
    days: "dias",
    monthsYear: {
      month01: (year) => `Jan/${year || yearNow}`,
      month02: (year) => `Fev/${year || yearNow}`,
      month03: (year) => `Mar/${year || yearNow}`,
      month04: (year) => `Abr/${year || yearNow}`,
      month05: (year) => `Mai/${year || yearNow}`,
      month06: (year) => `Jun/${year || yearNow}`,
      month07: (year) => `Jul/${year || yearNow}`,
      month08: (year) => `Ago/${year || yearNow}`,
      month09: (year) => `Set/${year || yearNow}`,
      month10: (year) => `Out/${year || yearNow}`,
      month11: (year) => `Nov/${year || yearNow}`,
      month12: (year) => `Dez/${year || yearNow}`,
    },
    createAVehicleToBegin: "Crie um veículo para começar",
    addressStart: "Endereço inicial",
    addressEnd: "Endereço final",
    address_start: "Endereço inicial",
    address_end: "Endereço final",
    noAddress: "Sem endereço",
    beginningNightPeriod: "Início do Período Noturno",
    endNightPeriod: "Fim do Período Noturno",
    day: "Dia",
    totalConductionTime: "Tempo total de condução",
    totalNightHours: "Horas totais noturnas",
    greaterContinuousDriving: "Maior condução contínua",
    learnMore: "Saiba mais.",
    distanceUnitOfDay: (distance_unit) => `${distance_unit} do dia`,
    realTotalExpenses: "Gasto Real Total",
    travelledDistance: "Distância Percorrida",
    cost: "Custo",
    kmReport: "Relatório - km Rodado",
    advancedFilters: "Filtros avançados",
    clearFilters: "Limpar filtros",
    clear: "Limpar",
    starDateMustBeGreaterThanEndDate: "A data inicial precisa ser maior que a data final.",
    totalTimeOn: "Tempo total ligado",
    realTotalCost: "Custo real total",
    startDate: 'Data de inicio',
    endDate: 'Data de término',
    routesReportDescription:
      "Com o Relatório de Rotas você tem acesso a todas as rotas dos Veículos em um determinado período, podendo visualizar por rotas ou por dia.",
    kmReportDescription:
      "O Relatório de km exibe a distância percorrida e o gasto real, de cada Veículo e o total da Frota.",
    driverPerDayReport: "Relatório - Motorista por dia",
    driverPerDayReportDesc:
      "Esse é um relatório detalhado de cada do Motorista por dia, com tempo de condução e distâncias percorridas.",
    totalTime: "Tempo total",
    daysStopped: "Dias Parado",
    situation: "Situação",
    vehicleSituation: "Situação do Veículo",
    totalDistance: "Distância total",
    startOdometer: "Odômetro inicial",
    endOdometer: "Odômetro final",
    totalCost: "Custo total",
    estimatedCost: "Custo Estimado",
    totalDuration: "Duração total",
    averageSpeed: "Velocidade média",
    maxSpeed: "Velocidade máxima",
    averageSpeedShort: "Vel. Média",
    maxSpeedShort: "Vel. Máx",
    init: "Início",
    end: "Fim",
    time: "Tempo",
    photo: "Foto",
    location: "Localizações",
    selectAVehicleState: "Selecione o estado do veículo",
    totalDistanceShort: "Distância",
    driverPerRouteReport: "Relatório - Motorista por rota",
    driverPerRouteReportDesc:
      "Esse é um relatório detalhado de cada rota realizada pelo Motorista, no período desejado.",
    showAllRoutesOnMap: "Rotas por dia",
		theseOptionsDependAtLeastOneRouteCompletedToBeEnabled: "Essas opções dependem de ao menos uma rota finalizada neste veículo para serem habilitadas",
    showAddresses: "Mostrar endereços",
    averageTotalTimeOnStops: "Tempo médio das paradas",
    totalTimeOffInRoutes: "Tempo total parado",
    productivityReport: "Relatórios - Produtividade",
    productivityReportDesc:
      "Esse relatório mostra o tempo que o Veículo ficou desligado entre uma rota e outra por dia, desde o início da jornada e o final da jornada.",
    routeStopTime: "Fim da Última Rota",
    initRoute: "Início da Próxima Rota",
    userAccess: "e acesse seu usuário com o PIN",
    statusReport: {
			noRule: "Nenhuma regra",
			equalTo: "Igual à",
			greaterThan: "Maior que",
			lessThan: "Menor que",
			writeDaysQuantity: "Digite a quantidade de Dias",
      totalVehicles: "Total de Veículos",
      totalIdleLesserThan7Days: "Parados a MENOS de 7 dias",
      totalIdleGreatherThan7Days: "Parados a MAIS de 7 dias",
      totalNoModule: "Módulos não instalados",
      totalUnderMaintance: "Veículo em Manutenção",
      totalChangeTracker: "Trocar Rastreador",
      totalNoUse: "Veículo sem uso",
      searchRule: "Regra de busca",
      descriptionStatus: "O Status do Veículo, como Ligado, Desligado, Sem sinal no momento ou Sem sinal já mais de 24 horas.",
      descriptionBlocked: "Em Bloqueado, é possível visualizar se o Veículo está Desbloqueado ou Bloqueado. Utilize essa função com cautela.",
      descriptionStage: `No Estágio do Veículo, você consegue verificar e definir o Veículo que está em “Funcionamento normal”, “Rastreador sem comunicação” ou “Manutenção”.
			Isso ajudará a identificar no Mapa e Relatórios esses Veículos.`,
    },
    kmReportToolTip:{
      noSignal:{
        text:"Veículo em área de Sombra.",
        link:"https://help.contelerastreador.com.br/pt-br/article/status-dos-veiculos-ligado-desligado-sem-sinal-e-mais-67hmpc/"
      },
      noSignal24:{
        text:"Veículo em área de Sombra por mais de 24 horas.",
        link:"https://help.contelerastreador.com.br/pt-br/article/status-dos-veiculos-ligado-desligado-sem-sinal-e-mais-67hmpc/"
      },
      noCommunication:{
        text:"Veículo sem comunicação com o Sistema por mais de 3 dias.",
        link:"https://help.contelerastreador.com.br/pt-br/article/status-dos-veiculos-ligado-desligado-sem-sinal-e-mais-67hmpc/"
      },
      noUse:{
        text:'Veículo em Estágio "Sem utilização", por determinação do Gestor da frota no Relatório de Status.',
        link:"https://help.contelerastreador.com.br/pt-br/article/status-dos-veiculos-ligado-desligado-sem-sinal-e-mais-67hmpc/"
      },
    },
    timeOff: "Tempo desligado",
    allDriversReport: "Relatório - Todos os motoristas",
    allDriversReportDesc:
      "Esse relatório é o consolidado de horas de condução, noturnas e distâncias percorridas pelos seus Motoristas.",
    totalNight: (alias) => {
      return `Total noturna (${alias})`;
    },
    months: "Meses",
    selectPeriodStartEnd: 'Selecione um perido de inicio e fim',
    greaterContinuousDrivingHour: "Tempo de maior condução contínua",
    totalConductionHours: "Horas totais de condução",
    includeAddresses: "Incluir endereços",
    auditReport: "Relatório - Auditoria",
    auditReportDesc:
      "Esse é um relatório completo e minucioso, que te mostra ponto a ponto todas as informações que o rastreador do Veículo enviou ao sistema.",
    yourReportIsReady: "Seu relatório está pronto!",
    yourDownloadInitiateAutomaticate:
      "Seu download será iniciado automaticamente. Caso não inicie, ",
    haveAnyDoubts: "Está com alguma dúvida?",
    clickHere: "clique aqui",
    sendViaEmail: "Enviar por e-mail",
    sendViaWhatsapp: "Enviar por WhatsApp",
    whatsapp: "WhatsApp",
    copyLink: "Copiar Link",
    sendViaApp: "Enviar para App",
    send: "Enviar",
    refreshAutomatic: "Atualização automática",
    eventsReport: "Relatório - Eventos",
    eventsReportDesc:
      'Esse relatório mostra todos os registros de Eventos dos Veículos da sua frota.',
    eventsReportLinkText:
      "Saiba como receber esses eventos por e-mail: Gerenciamento de Frotas somente por e-mail, é possível?",
    viewOnMap: "Ver no mapa",
    eventType: "Tipo de evento",
    moreInfo: "Mais informações",
    configured: "Configurado",
    realized: "Realizado",
    morning: "Manhã",
    afternoon: "Tarde",
    evening: "Noite",
    night: "Madrugada",
		noResultsFound: "Nenhum resultado encontrado",
		checkVehicleNameOrDriverIsCorrect: "Verifique se o Nome do Veículo ou Motorista está correto",
    noEventsFound: "Nenhum evento encontrado",
    noRegistersFound: "Nenhum registro encontrado",
    consumptionMonthDesc:
      "Você também pode efetuar um cadastro de abastecimento pelo APP Contele Driver ou Contele Rastreador.",
    monthCostDesc:
      "Esse relatório mostra custo e a quantidade de litros abastecidos por mês para todos os veículos da frota.",
    searchByKeyword: "Procurar por palavra-chave",
    fuelRegistersDesc:
      "Você também pode efetuar um cadastro de Abastecimento pelo APP Contele Driver ou Contele Rastreador.",
    typeEvents: {
      all: "Todos",
      speedInFence: "Excesso de velocidade na cerca",
      speed: "Excesso de velocidade",
      power: "Rastreador desconectado do veículo",
      sensor: "Sensores",
      'sensor 2': "Sensor 2",
      'sensor 3': "Sensor 3",
      'sensor 4': "Sensor 4",
      'sensor 5': "Sensor 5",
      driverNotIdentified: "Motorista não identificado",
      km: "km atingido",
      fence: "Cerca eletrônica",
      fenceIn: "Cerca eletrônica",
      fenceOut: "Cerca eletrônica",
      schedule: "Fora do horário",
      idle: "Veículo parado com motor ligado",
    },
    in: " na ",
    minuteS: " minuto(s)",
    hoursS: " hora(s)",
    emptyStateSubtitle: "Revise os filtros e tente buscar novamente.",
    errorHourOfWrongOrder: "O horário de início não pode ser posterior ou igual ao horário de término.",
    emptyStateTitle: "Nenhum registro encontrado no período selecionado!",
    maxSpeedReachedFrom: (speed, format) =>
      `Velocidade máxima de ${speed} ${format} ultrapassada`,
    routeReportDetailed: "Relatório detalhado de rota",
    detailed: "Detalhado",
    noEventsReportFound: "Nenhum evento encontrado",
    eventsParsers: {
      fenceName: (alias) => {
        return `Cerca "${alias}"`;
      },
      in: "Entrou na cerca eletrônica",
      out: "Saiu da cerca eletrônica",
      inOrOut: "Entrada ou saida"
    },
    minutes: "minutos",
    checklistItens: "Itens do checklist",
    errors: {
      dateIsRequired: "A data é obrigatória",
      vehiclesIsRequired: "Os veículos são obrigatórios",
      driversIsRequired: "Os motoristas são obrigatórios",
      ThisNameIsAlreadyBeingUsedInAnotherDriver:
        "Este nome já está sendo usado por outro motorista",
      trackerNotSupportCommand: (commandName, vehicleName) => {
        return `O comando ${commandName} não é suportado para o veículo ${vehicleName}`;
      },
      "This email is already being used in another user":
        "O email já foi cadastrado",
      routesNotFoundForSelectedPeriod:
        "Não há rotas para o período selecionado",
      errorOnGenerateReport: "Erro ao gerar relatório",
      fuelPriceMax: (decimalSeparator = ',') => `O valor do combustível não deve ultrapassar 100${decimalSeparator}00`,
      averageFuelMax: (decimalSeparator = ',') => `O valor médio de combustível não deve ultrapassar 100${decimalSeparator}00`
    },
    dayOfWeek: (day) => {
      let returnDay = "";
      switch (day) {
        case 0:
          returnDay = "Domingo";
          break;
        case 1:
          returnDay = "Segunda-feira";
          break;
        case 2:
          returnDay = "Terça-feira";
          break;
        case 3:
          returnDay = "Quarta-feira";
          break;
        case 4:
          returnDay = "Quinta-fera";
          break;
        case 5:
          returnDay = "Sexta-feira";
          break;
        case 6:
          returnDay = "Sábado";
          break;
        default:
          break
      }

      return returnDay;
    },
    getDayAndTimeToReport: (day, initTime, endTime) => {
      return localizedStrings.dayOfWeek(day) + ` (${initTime} às ${endTime}),`;
    },
    at: " às ",
    fully: "Cheio",
    noDriverOrRouteFound: "Nenhum motorista ou rota encontrada",
    ignition: "Ignição",
    ignitionOn: "Ligada",
    ignitionOff: "Desligada",
    rele: "Rele",
    sensors: "Sensores",
    sensor: "Sensor",
    speedKMH: "Velocidade km/h",
    traveledTime: "Tempo percorrido",
    distance: "Distância",
    localization: "Localizacao",
    completeName: "Nome completo",
    yes: "Sim",
    no: "Não",
    monthsPerNumber: {
      1: "Janeiro",
      2: "Fevereiro",
      3: "Março",
      4: "Abril",
      5: "Maio",
      6: "Junho",
      7: "Julho",
      8: "Agosto",
      9: "Setembro",
      10: "Outubro",
      11: "Novembro",
      12: "Dezembro",
    },
    reportsExport: {
			brand: "Marca",
      manufacturer: "Fabricação",
      total_value: "Valor",
      vehicle_name: "Nome Do Veículo",
      total_average: "Média",
      driver_name: "Nome Do Motorista",
      fully_filled: "Tanque",
      expire_driver_license_not_found: "Data vencimento do CNH não encontrada.",
	    liter_value: "Valor por litro",
      type_fuel_name: "Tipo de Combustível",
      reportAuditFileName: "relatorio-auditoria",
      reportAuditTabName: "relatorio-auditoria",
      reportKMFileName: "relatorio-km",
      ignition: "Ignicao",
      ignitionOn: "Ligada",
      ignitionOff: "Desligada",
      start_odometer: "Odometro Inicial",
      end_odometer: "Odometro Final",
      odometer: "Odometro",
      distance: "Distancia",
      speed: "Velocidade",
      total_distance: "Dist. Total",
      driver: "Motorista",
			CNHExpired: 'CNH Vencida',
			driverNotIdentified: "Não identificado",
      address: "Endereco",
      rele: "Rele",
      sensor: "Sensor",
      localization: "Localizacao",
      date: "Data",
			lastRecord: "Último registro",
      hour: "Hora",
      fullHour: "Horário",
      vehicle: "Veiculo",
      vehicle_plate: "Placa",
      vehicle_model: "Modelo",
      model_of_vehicle: "Modelo do veículo",
      cost: "Custo",
      group: "Grupo",
      avg_speed: "Vel. Media",
      max_speed: "Vel. Max",
      start: "Inicio",
      end: "Fim",
      time: "Tempo",
      start_address: "Endereco inicial",
      end_address: "Endereco final",
      name: "Nome",
      idName: "ID - Nome",
      year_manufacturer: "Ano do veículo",
      vehicle_type: "Tipo do veículo",
      plate_number: "Placa do Veículo",
      vehicle_groups: "Grupos",
      status: "Status",
      daysStopped: "Dias parado",
      command: "Comando",
			blocked: "Bloqueado",
			yes: "Sim",
			no: "Não",
			vehicleStage: "Estágio do Veículo",
      state: "Estado",
      contract: "Contrato",
      module: "Modulo",
      tank: "Tanque",
      fuelValue: "Valor Combustivel",
      fuelConsumption: "Consumo Combustivel",
      fuelType: "Tipo Gasolina",
      fuel_observation:"Observação",
      vehicleType: "Tipo Veiculo",
      emails: "Emails",
      docsLink: "Link Documentacao",
      maxSpeedAllowed: "Velocidade Maxima Permitida",
      maxEngineRunnningTime: "Tempo Maximo Motor Ligado",
      groups: "Grupos",
      usageSchedule: "Horario Utilizacao",
      checklist_items: "Items do checklist",
			observation: "Observação",
      totalCondutionTimeInHour: "Horas Totais de conducao",
      longestCondutionTime: "Maior conducao continua",
      day: "Dia",
      drivingTime: "Tempo total de condução",
      km_of_day: "km do dia",
      average: "Media",
      month: "Mes",
      liters: "Litros",
      quantity: "Quantidade",
      total_cost: "Custo total",
      cost_per_liter: "Custo por litro",
      route_stop: "Parada da rota",
      route_start: "Inicio da rota",
      time_off: "Tempo desligado",
      nickname: "Apelido",
      telephone: "Telefone",
      idCode: "Código de Identificação",
      CNH: "Numero de CNH",
      CNHExpirationDate: "Data de vencimento da CNH",
      email: "Email",
      value: "Valor",
      fuel: "Combustivel",
      event: "Evento",
      realized: "Realizado",
      more_informations: "Mais Informacoes",
      true_average: "Media Real",
      code: "Codigo",
      client: "Cliente",
      service: "Servico",
      stopPoints: "Pontos de parada",
      period: "Periodo",
      reason: "Motivo",
      configured_departure: "Horário Prog.",
      real_departure: "Horário Real",
      day_of_the_week: "Dia da semana",
      service_period: "Periodo",
      driver_name: "Motorista",
      vehicle_name: "Veiculo",
      service_start: "Horario Inicial",
      inicial_odometer: "Odometro Inicial",
    },
    loginPage: {
      yetDontUseContent: "Ainda não usa Contele Rastreador?",
      knowServices: "Clique aqui para conhecer nossos serviços",
      landingPageLink:
        "https://contelerastreador.com.br/?utm_medium=system-login",
      meetContele: "Conheça o Contele Rastreador!",
      whoWeAre: "Quem somos?",
      whoWeAreText: `O contele Rastreador é um sistema onde você tem <span style="font-weight:bold">total controle da sua frota.</span>`,
      topics: [
        "• Gestão Simplicada da frota;",
        "• Monitoramento de frota em Tempo Real;",
        "• Controle de Abastecimentos e Manutenção;",
        "• Digitalize as Operações da Frota;",
        "• Aplicativo dos Motoristas;",
        "• Reduza Gastos com Multas;",
        "• Determine onde seus veículos podem trafegar;",
      ],
      userInactive: "Usuário desativado",
      organizationInactive: "Organização desativada",
      somethingUnexpectedHappen: "Algo inesperado aconteceu. Tente novamente em alguns instantes.",
    },
    noDriveCreated: 'Sem motorista cadastrado',
    noGroupCreated: 'Sem grupo cadastrado',
    noEmailCreated: 'Sem e-mail cadastrado',
    noVehicleCreated: 'Sem veiculo cadastrado',
    noClientCreated: 'Sem cliente cadastrado',
    areYouSureUWantToDelete: 'Tem certeza que deseja deletar esse item?',
    noOptions: 'Sem opções cadastradas',
    attention: "Atenção",
    areYouSureUWantToSendCommandToThisVehicle: "Tem certeza que deseja enviar o comando?",
    vehicleIsInShadowArea: "Veículo(s) em Área de Sombra",
    areYouSureDeleteThis: "Tem certeza que deseja excluir?",
    thisActionNotIsReversive:{
        thisAction: "Esta ação apagará o presente",
        notIsReversive: "sem a possibilidade de restauração.",
    },
    doYouWantToProceed:"Deseja prosseguir?",
    operationCanceled: "Operação Cancelada",
    logisticService: {
      selectOptions: "Selecione uma das opções",
      all: "Todos",
      exportLogisticService: "Exportar de Serviço Logístico",
      selectOneLogisticService: "Selecione um Serviço Logístico",
      thisLogisticServiceStatus: "Status deste Serviço Logístico",
      manualDeparture: "Horário Manual",
      manualDepartureInfoOne: "Com o Horário Manual Ativado, você pode definir o horário de Embarque e Desembarque de cada Ponto de Parada.",
      manualDepartureInfoTwo: "É obrigatório que todos os Pontos de Parada tenham um horário definido.",
      caution: "Atenção:",
      hour: "Horário",
      name: "Nome",
      identification: "Identificação",
      inout: "Embarque/Desembarque",
      drivingPeriod: 'Período que irá dirigir',
      exception_create: {
        header: "Ajuste de embarque ou coleta: ",
        name: "Nome: ",
        orientation: "Digite abaixo o novo endereço de embarque: ",
        utilizationPeriod: "Data de utilização do Ajuste",
        zipcode: "CEP",
        zipcodePlaceHolder: "Digite o novo Cep",
        address: "Endereço",
        addressPlaceHolder: "Endereço de embarque",
        neighborhood: "Bairro",
        neighborhoodPlaceHolder: "Selecione um bairro",
        city: "Cidade",
        cityPlaceHolder: "Selecione a Cidade",
        number: "Número",
        numberPlaceHolder: "Digite o número",
        complement: "Complemento",
        complementPlaceHolder: "Digite um complemento",
        apply: "Aplicar Ajuste",
        editApply: "Editar Ajuste",
      },
      detail_route: {
        detail: 'Detalhe',
        path: 'Trajeto',
      },
      convert_status: {
        active: 'Concluido',
        not_started: 'Não iniciado',
        in_progress: 'Andamento',
        paused: 'Pausado',
        finished: 'Concluido',
        inactive: 'Desativado'
      },
      error: {
        deleteService: 'Erro ao deletar o serviço.',
        progressError: 'Erro ao atualizar o progresso.',
      },
      way: 'Trajeto',
      disableLogistics: 'Desabilitar serviço logistico.',
      inOutTheSame: 'Atenção: O endereço de embarque é igual ao de desembarque.',
      selectPeriodStartEnd: 'Selecione um perido de inicio e fim',
      addDriver: 'Adicionar motorista',
      createService: 'Cadastrar Serviço',
      noLogisticsFound: 'Nenhum serviço encontrado',
      logisticsServiceDescription: 'Gerenciar',
      logisticsService: 'Serviço Logístico',
      allServices: 'Todos os Serviços',
      description: 'Veja a listagem de Serviços Logísticos, cadastre novos, editar, organizar Rotas e ver o Status de cada serviço.',
      actions: 'Ações',
      identificator: 'Cód.',
      vehicle_name: 'Veículo',
      client_name: 'Cliente',
      driver_name: 'Nome do motorista',
      driver: 'Motorista',
      drivingDays: 'Dias que irá dirigir',
      driverNamePlaceHolder: 'Selecione um motorista',
      type_service_name: 'Tipo de Serviço',
      service_name: 'Serviço',
      start_end_formated: 'Periodo',
      end_date: 'Data Final',
      status: 'Status',
      places_quantity: 'Pontos de Parada',
      overview: 'Visão geral',
      drivers: 'Motoristas',
      stopPlaces: 'Pontos de parada',
      routeMap: 'Mapa da rota',
      clientLink: 'Código de acesso',
      serviceType: 'Tipo de serviço',
      placeholderServiceType: 'Transporte de passageiros',
      waitingTime: 'Tempo de embarque e desembarque',
      waitingTimePlaceholder: 'Tempo de embarque e desembarque',
      clientPlaceholder: 'Busque um cliente',
      hourPlaceholder: 'Selecione um horario',
      startDate: 'Data de inicio',
      endDate: 'Data Final',
      daysOfTheWeek: 'Dias da semana',
      daysOfTheWeekPlaceholder: 'Selecione os dias da semana',
      periodPlaceholder: 'Selecione o período',
      inicial_destiny: 'Destino inicial',
      end_destiny: 'Destino final',
      type: 'Ativar volta',
      hour_departure: 'Horário da ida',
      hour_return: 'Horário da volta',
      noServiceDriversFound: 'Não foi encontrado motoristas',
      noServiceStopPlacesFound: 'Não foi encontrado pontos de parada',
      address: 'Endereço',
      sunday: 'Domingo',
      monday: 'Segunda-Feira',
      tuesday: 'Terça-Feira',
      wednesday: 'Quarta-Feira',
      thursday: 'Quinta-Feira',
      friday: 'Sexta-Feira',
      saturday: 'Sábado',
      yes: 'Sim',
      no: 'Não',
      add: 'Adicionar',
      local_name: 'Local',
      identification: 'Identificação',
      tag_name: 'Etiqueta',
      localPlaceHolder: 'Selecione um local',
      clientPlaceHolder: 'Selecione um cliente',
      notFoundClientPlaces: 'Não existe locais nesse cliente.',
      notFoundTagPlaces: 'Não existe locais nessa etiqueta.',
      totalStops: 'Total de paradas: ',
      pathIniciate: 'Trajeto de ida iniciou as ',
      pathBack: 'Trajeto de volta iniciou as ',
      going: 'Ida',
      reorganizeStopPlace: 'Reorganizar Pontos',
      goback: 'Volta',
      boarding: 'Embarque',
      landing: 'Desembarque',
      hourBoarding: 'Horário de embarque',
      hourLanding: 'Horário de desembarque',
      expectedOutward: 'Ida Prevista',
      expectedTurn: 'Volta Prevista',
      noStopsConfigured: 'Sem paradas cadastradas',
      accessLink: 'Link para acesso',
      wating: 'Aguardando',
      shipped: 'Embarcado',
      arrived: 'Desembarcado',
      notShipped: 'Não Embarcou',
      nextStop: 'Próxima parada',
      driverOnTheWay: 'Motorista a caminho',
      begining: 'Inicio',
      end: 'Fim',
      until: 'até',
      manageLink: 'https://help.contelerastreador.com.br/pt-br/article/servicos-logisticos-u15po/',
      typeServiceInfo: 'Você poderá criar ou adicionar um Tipo de Serviço, podendo ser personalizável. Isso serve para categorizar os Serviços, possibilitando a fácil identificação em relatórios.',
      typeServiceInfoLink: 'https://help.contelerastreador.com.br/pt-br/article/servicos-logisticos-u15po/',
      departureReturnInfo: 'Tempo em que o Veículo ficará parado entre um ponto de parada e outro. Esse tempo será somado na estimativa do tempo da rota. Saiba Mais.',
      departureReturnInfoLink: 'https://help.contelerastreador.com.br/pt-br/article/servicos-logisticos-u15po/.',
      timeInicialFinalDestinyInfo: 'Selecione o período de vigência do serviço.',
      timeInicialFinalDestinyInfoLink: 'https://help.contelerastreador.com.br/pt-br/article/servicos-logisticos-u15po/',
      daysOfTheWeekInfo: 'Você poderá criar ou adicionar um Tipo de Serviço, podendo ser personalizável. Isso serve para categorizar os Serviços, possibilitando a fácil identificação em relatórios.',
      daysOfTheWeekInfoLink: 'https://help.contelerastreador.com.br/pt-br/article/servicos-logisticos-u15po/',
      inicialDestinyInfo: 'O ponto de partida do Veículo para o serviço.',
      inicialDestinyInfoLink: 'https://help.contelerastreador.com.br/pt-br/article/servicos-logisticos-u15po/',
      endDestinyInfo: 'O endereço final da rota do serviço.',
      endDestinyInfoLink: 'https://help.contelerastreador.com.br/pt-br/article/servicos-logisticos-u15po/',
      activeGoingEndDestinyInfo: 'Caso seja necessário, ative essa função para configurar um retorno, como por exemplo, transporte de passageiros. Escolha o horário da ida (saída do destino inicial para o destino final), e horário de volta (Saída do destino final para o destino inicial).',
      activeGoingEndDestinyInfoLink: 'https://help.contelerastreador.com.br/pt-br/article/servicos-logisticos-u15po/',
      clientSelectedInfo: 'Busque por um Cliente e carregue todos os Locais associados ao Cliente.',
      clientSelectedInfoLink: 'https://help.contelerastreador.com.br/pt-br/article/servicos-logisticos-u15po/',
      placeSelectedInfo: 'Busque por um Local específico.',
      placeSelectedInfoLink: 'https://help.contelerastreador.com.br/pt-br/article/servicos-logisticos-u15po/',
      inputDateInfo: 'Você poderá selecionar os dias que deseja, podendo verificar o detalhamento e o histórico dos serviços',
      inputDateInfoLink: 'https://help.contelerastreador.com.br/pt-br/article/servicos-logisticos-u15po/',
      tagInfo: 'Busque por uma Etiqueta e carregue todos os Locais associados à Etiqueta.',
      tagInfoLink: 'https://help.contelerastreador.com.br/pt-br/article/servicos-logisticos-u15po/',
      minutes: 'min',
      type_service_create: {
        sucess_create_service: 'Tipo de Serviço criado com sucesso.',
        error_create_type_service: 'Erro ao criar tipo de serviço. Tente novamente mais tarde.',
        deleteService: 'Erro ao deletar o serviço.',
      },
      service_edit: {
        title: 'Gerenciar',
        page_title: 'Edição Serviço Logístico',
        subtitle: 'Edição Serviço Logístico',
        sucess: 'Serviço Logístico atualizado com sucesso.',
        error: 'Erro ao atualizar serviço logístico. Tente novamente mais tarde.',
        deactivateToolTip: 'Ao desativar essa função, a rota não será listada no itinerário do motorista.',
        activatedStatus:'Ativado',
        deactivatedStatus:'Desativado',
      },
      service_create: {
        title: 'Gerenciar',
        page_title: 'Cadastro Serviço Logístico',
        subtitle: 'Cadastro Serviço Logístico',
        typeServiceName: 'Nome do tipo de serviço',
        typeServiceNamePlaceholder: 'Digite o tipo do nome do serviço',
        timeDepartureReturn: 'Tempo de Embarque e Desembarque',
        timeDepartureReturnPlaceholder: 'Selecione o tempo de embarque e desembarque',
        addTypeService: 'Adicionar um Tipo de Serviço',
        sucess: 'Serviço Logístico criado com sucesso.',
        error: 'Erro ao criar serviço logístico. Tente novamente mais tarde.',
      },
      placeLimit: "Somente é permitido 200 locais no total."
    },
    solicitationStatus: {
      pending: "Pendente",
      approved: "Aprovado",
      recused: "Recusado",
      inactive: "Inativo",
    },
    solicitationActionsByStatus: {
      pending: {
        approve: "Aprovar",
        recuse: "Recusar",
      },
    },
    to: "Para",
    solicitationPeriod: {
      to: "até",
      from: "das",
    },
    solicitationExport: {
      descr: "Descrição",
      start_date: "Data de inicio",
      end_date: "Data de término",
      descr_recused: "Motivo",
      user_name: "Usuário Solicitante",
      created: "Data de criação",
      driver_name: "Motorista",
      vehicle_name: "Veículo",
      status_translated: "Status",
    },
    modalBillet: {
      dueDate: "Data de Vencimento",
      talkToUs: "Fale conosco no",
      orInSystemChat: "ou aqui no Chat do Sistema",
      makePayment: "Realizar Pagamento",
      blockedAccess: {
        title: "Seu acesso ao sistema está bloqueado",
        text1: "Por onde os seus <span style='font-weight:bold'>veículos</span> passaram nos últimos dias?",
        text2: "Nos últimos 30 dias na sua empresa você nao viu:",
        item1: "Os novos registros de <span style='font-weight:bold'>Abastecimentos</span>;",
        item2: "Quantos km's de <span style='font-weight:bold'>Rotas</span> foram percorridas;",
        item3: "Os <span style='font-weight:bold'>Checklists</span> registrados;",
        item4: "Quais foram os <span style='font-weight:bold'>Eventos<span> notificados;",
        text3: "Volte a ter o controle na sua mão, reduzindo os custos e aumentando a produtividade;",
      },
      billetAvailableForPayment: {
        title: "Boleto dísponivel para pagamento",
        text: "Para sua comodidade já disponibilizamos seu boleto para pagamento. Programe o pagamento e mantenha seus descontos."
      },
      billetCloseToDueDate: {
        title: "Boleto próximo ao vencimento",
        text: "Seu boleto está próximo ao vencimento. Programe o pagamento e mantenha seus descontos."
      },
      billetWillWinToday: {
        title: "Boleto vencerá hoje",
        text: "Para sua comodidade já disponibilizamos seu boleto que <span style='font-weight:bold'>vencerá hoje</span> para pagamento. Programe o pagamento e mantenha seus descontos."
      },
      billetExpired1: {
        title: "Seu Boleto está vencido",
        text: "O boleto do Contele Rastreador venceu há 1 dia. Evite o bloqueio da sua conta e o acesso aos dados dos seus veículos."
      },
      billetExpired5: {
        title: "Seu Boleto está vencido",
        text: "O boleto do Contele Rastreador venceu há 5 dias. Evite o bloqueio da sua conta e o acesso aos dados dos seus veículos."
      }
    },
    attach_driver: {
      attachDriverToRoute: "Associar Motorista a Rota",
      date: "Data",
      inicialAddress: "End. Inicial",
      endAddress: "End. Final",
      searchByDriver: "Busque por um ou mais Motoristas para associar a Rota:",
      attachDriver: "Associar Motorista",
      dontFindDriver: "Não achou o Motorista? ",
      clickHere: "Clique aqui ",
      toCreate: "para cadastrar.",
      addDriver: "Adicione um Motorista",
    },
    noneOnTheRecord: "Nenhum Cadastrado",
    tooltipAttachDriver: "Clique para associar Motorista",
    successAttachDriver: "Motorista associado com sucesso.",
    errorAttachDriver: "Não foi possivel associar o motorista a rota, tente novamente.",
    addressRouteNotFound: "Endereço não encontrado",
    notFound: "Não encontrado",
  },
});
const [userLang] = (navigator.language || navigator.userLanguage).split("-");
export { localizedStrings, userLang };
