import { localizedStrings } from "./localizedStrings";

const formatObject = object =>
  Object.keys(object).map(item => ({
    value: item,
    label: object[item]
  }));

let moduleOptions = {
  language: [
    {
      value: "pt",
      label: "Português"
    },
    {
      value: "es",
      label: "Espanhol"
    },
    {
      value: "en",
      label: "Inglês"
    }
  ],
  currency: [
    { value: "BRL", label: "Real", unit: "R$" },
    { value: "CLP", label: "Peso chileno", unit: "$" },
    { value: "COP", label: "Peso colombiano", unit: "$" },
    { value: "MXN", label: "Peso mexicano", unit: "$" },
    { value: "USD", label: "Dólar americano", unit: "$" },
    { value: "EUR", label: "Euro", unit: "€" }
  ],
  distanceUnit: [
    { value: "km", label: "km" },
    { value: "mi", label: "milhas" }
  ],
  volumetricUnit: [
    { value: 1, label: "ℓ - Liter", unit: "ℓ"},
    { value: 2, label: "fl oz - Fluid ounce" , unit: "fl oz"},
    { value: 3, label: "gill - Gill" , unit: "gill"},
    { value: 4, label: "pt - Pint" , unit: "pt"},
    { value: 5, label: "qt - Quart" , unit: "qt"},
    { value: 6, label: "gal - Gallon", unit: "gal" }
  ],
  timeFormat: [
    { value: "HH:MM:SS", label: "HH:MM:SS" , unit: "HH"},
    { value: "HH:MM", label: "HH:MM" },
    { value: "HH24:MM:SS", label: "HH24:MM:SS" },
    { value: "HH24:MM", label: "HH24:MM" }
  ],
  decimal: [
    {
      value: ",",
      label: ","
    },
    {
      value: ".",
      label: "."
    }
  ],
  distance: [
    {
      value: "km",
      label: "km"
    },
    {
      value: "mi",
      label: "milhas"
    }
  ],
  thousand: [
    {
      value: ",",
      label: ","
    },
    {
      value: ".",
      label: "."
    }
  ],
  dateFormat: [
    {
      value: "DD/MM/YYYY",
      label: "DD/MM/YYYY"
    },
    {
      value: "MM/DD/YYYY",
      label: "MM/DD/YYYY"
    },
    {
      value: "YYYY/MM/DD",
      label: "YYYY/MM/DD"
    },
    {
      value: "DD/MM/YY",
      label: "DD/MM/YY"
    },
    {
      value: "MM/DD/YY",
      label: "MM/DD/YY"
    },
    {
      value: "YY/MM/DD",
      label: "YY/MM/DD"
    },
    {
      value: "DD-MM-YYYY",
      label: "DD-MM-YYYY"
    },
    {
      value: "MM-DD-YYYY",
      label: "MM-DD-YYYY"
    },
    {
      value: "DD-MM-YY",
      label: "DD-MM-YY"
    },
    {
      value: "MM-DD-YY",
      label: "MM-DD-YY"
    },
    {
      value: "DD-MM-YY",
      label: "DD-MM-YY"
    }
  ],
  type: [
  ],
  timezones: {
    "Pacific/Midway": "(GMT-11:00) Midway Island",
    "America/Tijuana": "(GMT-08:00) Tijuana",
    "America/Chihuahua": "(GMT-07:00) Chihuahua",
    "America/Mazatlan": "(GMT-07:00) Mazatlan",
    "America/Mexico_City": "(GMT-06:00) Mexico City",
    "America/Monterrey": "(GMT-06:00) Monterrey",
    "America/Bogota": "(GMT-05:00) Bogota",
    "America/Lima": "(GMT-05:00) Lima",
    "America/Caracas": "(GMT-04:30) Caracas",
    "America/La_Paz": "(GMT-04:00) La Paz",
    "America/Santiago": "(GMT-04:00) Santiago",
    "America/Sao_Paulo": "(GMT-03:00) Sao Paulo",
    "America/Buenos_Aires": "(GMT-03:00) Buenos Aires",
    "Atlantic/Stanley": "(GMT-02:00) Stanley",
    "Atlantic/Azores": "(GMT-01:00) Azores",
    "Atlantic/Cape_Verde": "(GMT-01:00) Cape Verde Is.",
    "Africa/Casablanca": "(GMT) Casablanca",
    "Europe/Dublin": "(GMT) Dublin",
    "Europe/Lisbon": "(GMT) Lisbon",
    "Europe/London": "(GMT) London",
    "Africa/Monrovia": "(GMT) Monrovia",
    "Europe/Amsterdam": "(GMT+01:00) Amsterdam",
    "Europe/Belgrade": "(GMT+01:00) Belgrade",
    "Europe/Berlin": "(GMT+01:00) Berlin",
    "Europe/Bratislava": "(GMT+01:00) Bratislava",
    "Europe/Brussels": "(GMT+01:00) Brussels",
    "Europe/Budapest": "(GMT+01:00) Budapest",
    "Europe/Copenhagen": "(GMT+01:00) Copenhagen",
    "Europe/Ljubljana": "(GMT+01:00) Ljubljana",
    "Europe/Madrid": "(GMT+01:00) Madrid",
    "Europe/Paris": "(GMT+01:00) Paris",
    "Europe/Prague": "(GMT+01:00) Prague",
    "Europe/Rome": "(GMT+01:00) Rome",
    "Europe/Sarajevo": "(GMT+01:00) Sarajevo",
    "Europe/Skopje": "(GMT+01:00) Skopje",
    "Europe/Stockholm": "(GMT+01:00) Stockholm",
    "Europe/Vienna": "(GMT+01:00) Vienna",
    "Europe/Warsaw": "(GMT+01:00) Warsaw",
    "Europe/Zagreb": "(GMT+01:00) Zagreb",
    "Europe/Athens": "(GMT+02:00) Athens",
    "Europe/Bucharest": "(GMT+02:00) Bucharest",
    "Africa/Cairo": "(GMT+02:00) Cairo",
    "Africa/Harare": "(GMT+02:00) Harare",
    "Europe/Helsinki": "(GMT+02:00) Helsinki",
    "Europe/Istanbul": "(GMT+02:00) Istanbul",
    "Asia/Jerusalem": "(GMT+02:00) Jerusalem",
    "Europe/Kiev": "(GMT+02:00) Kyiv",
    "Europe/Minsk": "(GMT+02:00) Minsk",
    "Europe/Riga": "(GMT+02:00) Riga",
    "Europe/Sofia": "(GMT+02:00) Sofia",
    "Europe/Tallinn": "(GMT+02:00) Tallinn",
    "Europe/Vilnius": "(GMT+02:00) Vilnius",
    "Asia/Baghdad": "(GMT+03:00) Baghdad",
    "Asia/Kuwait": "(GMT+03:00) Kuwait",
    "Africa/Nairobi": "(GMT+03:00) Nairobi",
    "Asia/Riyadh": "(GMT+03:00) Riyadh",
    "Europe/Moscow": "(GMT+03:00) Moscow",
    "Asia/Tehran": "(GMT+03:30) Tehran",
    "Asia/Baku": "(GMT+04:00) Baku",
    "Europe/Volgograd": "(GMT+04:00) Volgograd",
    "Asia/Muscat": "(GMT+04:00) Muscat",
    "Asia/Tbilisi": "(GMT+04:00) Tbilisi",
    "Asia/Yerevan": "(GMT+04:00) Yerevan",
    "Asia/Kabul": "(GMT+04:30) Kabul",
    "Asia/Karachi": "(GMT+05:00) Karachi",
    "Asia/Tashkent": "(GMT+05:00) Tashkent",
    "Asia/Kolkata": "(GMT+05:30) Kolkata",
    "Asia/Kathmandu": "(GMT+05:45) Kathmandu",
    "Asia/Yekaterinburg": "(GMT+06:00) Ekaterinburg",
    "Asia/Almaty": "(GMT+06:00) Almaty",
    "Asia/Dhaka": "(GMT+06:00) Dhaka",
    "Asia/Novosibirsk": "(GMT+07:00) Novosibirsk",
    "Asia/Bangkok": "(GMT+07:00) Bangkok",
    "Asia/Jakarta": "(GMT+07:00) Jakarta",
    "Asia/Krasnoyarsk": "(GMT+08:00) Krasnoyarsk",
    "Asia/Hong_Kong": "(GMT+08:00) Hong Kong",
    "Asia/Kuala_Lumpur": "(GMT+08:00) Kuala Lumpur",
    "Australia/Perth": "(GMT+08:00) Perth",
    "Asia/Singapore": "(GMT+08:00) Singapore",
    "Asia/Taipei": "(GMT+08:00) Taipei",
    "Asia/Ulaanbaatar": "(GMT+08:00) Ulaan Bataar",
    "Asia/Urumqi": "(GMT+08:00) Urumqi",
    "Asia/Irkutsk": "(GMT+09:00) Irkutsk",
    "Asia/Seoul": "(GMT+09:00) Seoul",
    "Asia/Tokyo": "(GMT+09:00) Tokyo",
    "Australia/Adelaide": "(GMT+09:30) Adelaide",
    "Australia/Darwin": "(GMT+09:30) Darwin",
    "Asia/Yakutsk": "(GMT+10:00) Yakutsk",
    "Australia/Brisbane": "(GMT+10:00) Brisbane",
    "Pacific/Guam": "(GMT+10:00) Guam",
    "Australia/Hobart": "(GMT+10:00) Hobart",
    "Australia/Melbourne": "(GMT+10:00) Melbourne",
    "Pacific/Port_Moresby": "(GMT+10:00) Port Moresby",
    "Australia/Sydney": "(GMT+10:00) Sydney",
    "Asia/Vladivostok": "(GMT+11:00) Vladivostok",
    "Asia/Magadan": "(GMT+12:00) Magadan",
    "Pacific/Auckland": "(GMT+12:00) Auckland",
    "Pacific/Fiji": "(GMT+12:00) Fiji"
  },
  country: {
    AD: "Andorra",
    AE: "Emirados Árabes Unidos",
    AF: "Afeganistão",
    AG: "Antígua e Barbuda",
    AI: "Anguilla",
    AL: "Albânia",
    AM: "Armênia",
    AO: "Angola",
    AQ: "Antártica",
    AR: "Argentina",
    AS: "Samoa Americana",
    AT: "Áustria",
    AU: "Austrália",
    AW: "Aruba",
    AZ: "Azerbaijão",
    BA: "Bósnia e Herzegovina",
    BB: "Barbados",
    BD: "Bangladesh",
    BE: "Bélgica",
    BF: "Burkina Faso",
    BG: "Bulgária",
    BH: "Barém",
    BI: "Burundi",
    BJ: "Benin",
    BL: "São Bartolomeu",
    BM: "Bermuda",
    BN: "Brunei",
    BO: "Bolívia",
    BR: "Brasil",
    BS: "Bahamas",
    BT: "Butão",
    BV: "Ilha Bouvet",
    BW: "Botswana",
    BY: "Belarus",
    BZ: "Belize",
    CA: "Canadá",
    CC: "Ilhas Cocos (Keeling)",
    CD: "Congo, República Democrática do",
    CF: "República Centro-Africana",
    CG: "Congo, República do",
    CH: "Suíça",
    CI: "Costa do Marfim",
    CK: "Ilhas Cook",
    CL: "Chile",
    CM: "Camarões",
    CN: "China",
    CO: "Colômbia",
    CR: "Costa Rica",
    CU: "Cuba",
    CV: "Cabo Verde",
    CW: "Curaçao",
    CX: "Ilha Christmas",
    CY: "Chipre",
    CZ: "República Tcheca",
    DE: "Alemanha",
    DJ: "Djibuti",
    DK: "Dinamarca",
    DM: "Dominica",
    DO: "República Dominicana",
    DZ: "Argélia",
    EC: "Equador",
    EE: "Estônia",
    EG: "Egito",
    EH: "Saara Ocidental",
    ER: "Eritréia",
    ES: "Espanha",
    ET: "Etiópia",
    FI: "Finlândia",
    FJ: "Fiji",
    FK: "Ilhas Falkland (Malvinas)",
    FM: "Micronésia, Estados Federados da",
    FO: "Ilhas Feroe",
    FR: "França",
    FX: "França Metropolitana",
    GA: "Gabão",
    GB: "Reino Unido",
    GD: "Grenada",
    GE: "Geórgia",
    GF: "Guiana Francesa",
    GG: "Guernsey",
    GH: "Gana",
    GI: "Gibraltar",
    GL: "Greenland",
    GM: "Gâmbia",
    GN: "Guiné",
    GP: "Guadelupe",
    GQ: "Guiné Equatorial",
    GR: "Grécia",
    GS: "Geórgia do Sul e Ilhas",
    GT: "Guatemala",
    GU: "Guam",
    GW: "Guiné-Bissau",
    GY: "Guiana",
    HK: "Hong Kong",
    HM: "Ilhas Heard and McDonald",
    HN: "Honduras",
    HR: "Croácia",
    HT: "Haiti",
    HU: "Hungria",
    ID: "Indonésia",
    IE: "Irlanda",
    IL: "Israel",
    IM: "Ilha de Man",
    IN: "Índia",
    IO: "Território Britânico do Oceano Índico",
    IQ: "Iraque",
    IR: "Irã",
    IS: "Islândia",
    IT: "Itália",
    JE: "Jersey",
    JM: "Jamaica",
    JO: "Jordânia",
    JP: "Japão",
    KE: "Quênia",
    KG: "Quirguistão",
    KH: "Camboja",
    KI: "Kiribati",
    KM: "Cômoros",
    KN: "São Cristóvão e Nevis",
    KP: "Coreia do Norte",
    KR: "Coreia do Sul",
    KW: "Kuwait",
    KY: "Ilhas Caiman",
    KZ: "Cazaquistão",
    LA: "Laos",
    LB: "Líbano",
    LC: "Santa Lúcia",
    LI: "Liechtenstein",
    LK: "Sri Lanka",
    LR: "Libéria",
    LS: "Lesoto",
    LT: "Lituânia",
    LU: "Luxemburgo",
    LV: "Letônia",
    LY: "Líbia",
    MA: "Marrocos",
    MC: "Mônaco",
    MD: "Moldova",
    ME: "Montenegro",
    MF: "Saint Martin",
    MG: "Madagascar",
    MH: "Ilhas Marshall",
    MK: "Macedônia",
    ML: "Mali",
    MM: "Birmânia",
    MN: "Mongólia",
    MO: "Macao",
    MP: "Ilhas Marianas do Norte",
    MQ: "Martinica",
    MR: "Mauritânia",
    MS: "Montserrat",
    MT: "Malta",
    mu: "Ilhas Maurício",
    MV: "Maldivas",
    MW: "Malawi",
    MX: "México",
    MY: "Malásia",
    MZ: "Moçambique",
    NA: "Namíbia",
    NC: "Nova Caledônia",
    NE: "Níger",
    NF: "Ilha Norfolk",
    NG: "Nigéria",
    NI: "Nicarágua",
    NL: "Holanda",
    NO: "Noruega",
    NP: "Nepal",
    NR: "Nauru",
    NU: "Niue",
    NZ: "Nova Zelândia",
    OM: "Omã",
    PA: "Panamá",
    PE: "Peru",
    PF: "Polinésia Francesa",
    PG: "Papua Nova Guiné",
    PH: "Filipinas",
    PK: "Paquistão",
    PL: "Polônia",
    PM: "Saint Pierre e Miquelon",
    PN: "Ilhas Pitcairn",
    PR: "Porto Rico",
    PS: "Cisjordânia",
    PT: "Portugal",
    PW: "Palau",
    PY: "Paraguai",
    QA: "Qatar",
    RE: "Reunião",
    RO: "Romênia",
    RS: "Sérvia",
    RU: "Rússia",
    RW: "Ruanda",
    SA: "Arábia Saudita",
    SB: "Ilhas Salomão",
    SC: "Seicheles",
    SD: "Sudão",
    SE: "Suécia",
    SG: "Cingapura",
    SH: "Santa Helena, Ascensão e Tristão da Cunha",
    SI: "Eslovênia",
    SJ: "Svalbard",
    SK: "Eslováquia",
    SL: "Serra Leoa",
    SM: "San Marino",
    SN: "Senegal",
    SO: "Somália",
    SR: "Suriname",
    SS: "Sudão do Sul",
    ST: "São Tomé e Príncipe",
    SV: "El Salvador",
    SX: "São Martinho",
    SY: "Síria",
    SZ: "Suazilândia",
    TC: "Ilhas Turks e Caicos",
    TD: "Chad",
    TF: "Sul da França e Antártica",
    TG: "Togo",
    TH: "Tailândia",
    TJ: "Tadjiquistão",
    TK: "Toquelau",
    TL: "Timor-Leste",
    TM: "Turcomenistão",
    TN: "Tunísia",
    TO: "Tonga",
    TR: "Turquia",
    TT: "Trinidad e Tobago",
    TV: "Tuvalu",
    TW: "Taiwan",
    TZ: "Tanzânia",
    UA: "Ucrânia",
    UG: "Uganda",
    UM: "Ilhas Menores Distantes dos Estados Unidos",
    US: "Estados Unidos",
    UY: "Uruguai",
    UZ: "Uzbequistão",
    VA: "Santa Sé (Cidade do Vaticano)",
    VC: "São Vicente e Granadinas",
    VE: "Venezuela",
    VG: "Ilhas Virgens Britânicas",
    VI: "Ilhas Virgens Americanas",
    VN: "Vietnã",
    VU: "Vanuatu",
    WF: "Ilhas Wallis e Futuna",
    WS: "Samoa",
    XK: "Kosovo",
    YE: "Iêmen",
    YT: "Maiote",
    ZA: "África do Sul",
    ZM: "Zâmbia",
    ZW: "Zimbábue"
  },
  formatDriversToSelect : (drivers) => {
    const formattedDrivers = [];
    // eslint-disable-next-line
    drivers.map(val => {
        let obj = {
            "value": val.id,
            "label": val.nome || val.nickname
        }
        formattedDrivers.push(obj);
    });
    return formattedDrivers;
  },
  formatVehiclesToSelect : (vehicles) => {
    const formattedVehicles = [];
    if(!Array.isArray(vehicles)) return;
    // eslint-disable-next-line
    vehicles.map(val => {
        let obj = {
            "value": val.id,
            "label": val.name
        }
        formattedVehicles.push(obj);
    });
    return formattedVehicles;
  },
  hours: [
    {index:0,label: "00:00", value: "00:00:00",},
    {index:1,label: "00:30", value: "00:30:00",},
    {index:2,label: "01:00", value: "01:00:00",},
    {index:3,label: "01:30", value: "01:30:00",},
    {index:4,label: "02:00", value: "02:00:00",},
    {index:5,label: "02:30", value: "02:30:00",},
    {index:6,label: "03:00", value: "03:00:00",},
    {index:7,label: "03:30", value: "03:30:00",},
    {index:8,label: "04:00", value: "04:00:00",},
    {index:9,label: "04:30", value: "04:30:00",},
    {index:10,label: "05:00", value: "05:00:00",},
    {index:11,label: "05:30", value: "05:30:00",},
    {index:12,label: "06:00", value: "06:00:00",},
    {index:13,label: "06:30", value: "06:30:00",},
    {index:14,label: "07:00", value: "07:00:00",},
    {index:15,label: "07:30", value: "07:30:00",},
    {index:16,label: "08:00", value: "08:00:00",},
    {index:17,label: "08:30", value: "08:30:00",},
    {index:18,label: "09:00", value: "09:00:00",},
    {index:19,label: "09:30", value: "09:30:00",},
    {index:20,label: "10:00", value: "10:00:00",},
    {index:21,label: "10:30", value: "10:30:00",},
    {index:22,label: "11:00", value: "11:00:00",},
    {index:23,label: "11:30", value: "11:30:00",},
    {index:24,label: "12:00", value: "12:00:00",},
    {index:25,label: "12:30", value: "12:30:00",},
    {index:26,label: "13:00", value: "13:00:00",},
    {index:27,label: "13:30", value: "13:30:00",},
    {index:28,label: "14:00", value: "14:00:00",},
    {index:29,label: "14:30", value: "14:30:00",},
    {index:30,label: "15:00", value: "15:00:00",},
    {index:31,label: "15:30", value: "15:30:00",},
    {index:32,label: "16:00", value: "16:00:00",},
    {index:33,label: "16:30", value: "16:30:00",},
    {index:34,label: "17:00", value: "17:00:00",},
    {index:35,label: "17:30", value: "17:30:00",},
    {index:36,label: "18:00", value: "18:00:00",},
    {index:37,label: "18:30", value: "18:30:00",},
    {index:38,label: "19:00", value: "19:00:00",},
    {index:39,label: "19:30", value: "19:30:00",},
    {index:40,label: "20:00", value: "20:00:00",},
    {index:41,label: "20:30", value: "20:30:00",},
    {index:42,label: "21:00", value: "21:00:00",},
    {index:43,label: "21:30", value: "21:30:00",},
    {index:44,label: "22:00", value: "22:00:00",},
    {index:45,label: "22:30", value: "22:30:00",},
    {index:46,label: "23:00", value: "23:00:00",},
    {index:47,label: "23:30", value: "23:30:00",},
    {index:48,label: "23:59", value: "23:59:59",},
  ],
  weekDays: [
    { id: 1, name: localizedStrings.monday, selected: false, disabled: false },
    { id: 2, name: localizedStrings.tuesday, selected: false, disabled: false },
    { id: 3, name: localizedStrings.wednesday, selected: false, disabled: false },
    { id: 4, name: localizedStrings.thursday, selected: false, disabled: false },
    { id: 5, name: localizedStrings.friday, selected: false, disabled: false },
    { id: 6, name: localizedStrings.saturday, selected: false, disabled: false },
    { id: 7, name: localizedStrings.sunday, selected: false, disabled: false },
]
};

moduleOptions.country = formatObject(moduleOptions.country);
moduleOptions.timezones = formatObject(moduleOptions.timezones);

export default moduleOptions;
